試合管理画面　UI-TableVIewCell実装
hidec-7/MySoccerNoteApp pull request #10
Opened 2020-11-12 07:20 UTC by hidec-7

**clone コマンド**
git clone -b feature/add-UI-TableViewCell https://github.com/hidec-7/SoccerNoteDev.git

**Trello**
試合管理画面 Xib TableViewCell: チーム・スコア・日付  実装

**概要**
試合管理画面のTableViewCellを実装
CellにAutoLayoutでLabelの貼り付け
TableViewとの紐付け

**レビューで見て欲しいポイント**
AutoLayoutが上手くできているか、UIに関して。
commitの名前に自信がないです。例えばこれならこう言う名前が良いかなと言ったアドバイスをもう一度頂けないでしょうか。

**実機build/期待通りの挙動をするか**
OK

※UI変更した場合のみ記述

**11 Pro や SE など大きさが異なる端末のレイアウトが崩れていないか？**
OK

**レビュー依頼**
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741

**補足**
後から気づいての修正や追記の余計なcommitが増えてしまいました。すいません。

2020-11-12 08:47 UTC, fuchi0741 commented
若干意地悪かもしれませんがSE(第一世代)で見るとレイアウトが崩れてしまっていますね、、、。

<img width="377" alt="スクリーンショット 2020-11-12 17 46 53" src="https://user-images.githubusercontent.com/50318372/98916927-1743f980-250f-11eb-9cb8-3223f819dce4.png">

2020-11-12 08:55 UTC, fuchi0741 commented
> AutoLayoutが上手くできているか、UIに関して。
サイズが大きいiPhoneに関しては問題がなさそうです！

AutoLayoutに関していうと、stackViewってやつをうまく使えると後々修正が楽な設計になります！
詳しくは調べてみてください！

例えば 
0 - 0
のところとかですかね、、、

ここは2、3年後も運用する前提ならやった方がいいですが、今回は個人開発なので任意にします！
あとはiPhoneSE対策も同じく修正は任意にしますー！
(AutoLayoutに詳しくなれるのがメリット、次の実装に行くまで時間がかかるのがデメリットです)

2020-11-12 08:56 UTC, fuchi0741 commented
あとこれも聞き流すレベルで大丈夫ですが、レイアウトの制約は8の倍数で設定するときれいに見えるって聞いたことがあります

2020-11-12 08:59 UTC, fuchi0741 commented
(提案ですが、AutoLayoutをガッツリやりたいってなったら一旦レクチャー会をした方が早いのではと思っています！)
AutoLayout自分も最初かなり苦戦した記憶なので笑

例えばですが、Opponent Team Label に widthを設定していますが設定する恩恵は特になさそうです。
理由は相手チームによってラベルのwidthが可変になるからです！

2020-11-12 09:03 UTC, fuchi0741 commented
あとcommitですが、自分が見る限り特に名称に問題はないです！

まあファイル名はできればさけた方がレビューした人がどこを修正したのかがわかるかなって程度です！

あと自分がcommitは細かい方がいい！ってアドバイスしておいて申し訳ないですが、
もう少しcommitをするタイミングに粒度がもう少し粗くてもいいかと思いました！mm

2020-11-12 09:25 UTC, hidec-7 commented
> 若干意地悪かもしれませんがSE(第一世代)で見るとレイアウトが崩れてしまっていますね、、、。
> 
> 
> 
> <img width="377" alt="スクリーンショット 2020-11-12 17 46 53" src="https://user-images.githubusercontent.com/50318372/98916927-1743f980-250f-11eb-9cb8-3223f819dce4.png">
> 
> 

あれ、自分で見たとき崩れてないと思ったんですけど違うのをビルドして見てたんですね笑

2020-11-12 09:25 UTC, hidec-7 commented
> > 若干意地悪かもしれませんがSE(第一世代)で見るとレイアウトが崩れてしまっていますね、、、。
> > 
> > 
> > 
> > <img width="377" alt="スクリーンショット 2020-11-12 17 46 53" src="https://user-images.githubusercontent.com/50318372/98916927-1743f980-250f-11eb-9cb8-3223f819dce4.png">
> > 
> > 
> 
> あれ、自分で見たとき崩れてないと思ったんですけど違うのをビルドして見てたんですね笑

2020-11-12 09:26 UTC, hidec-7 commented
> > AutoLayoutが上手くできているか、UIに関して。
> 
> サイズが大きいiPhoneに関しては問題がなさそうです！
> 
> 
> 
> AutoLayoutに関していうと、stackViewってやつをうまく使えると後々修正が楽な設計になります！
> 
> 詳しくは調べてみてください！
> 
> 
> 
> 例えば 
> 
> 0 - 0
> 
> のところとかですかね、、、
> 
> 
> 
> ここは2、3年後も運用する前提ならやった方がいいですが、今回は個人開発なので任意にします！
> 
> あとはiPhoneSE対策も同じく修正は任意にしますー！
> 
> (AutoLayoutに詳しくなれるのがメリット、次の実装に行くまで時間がかかるのがデメリットです)

なるほどです！

調べてみます！

少し考えてみますね！

2020-11-12 09:27 UTC, hidec-7 commented
> (提案ですが、AutoLayoutをガッツリやりたいってなったら一旦レクチャー会をした方が早いのではと思っています！)
> 
> AutoLayout自分も最初かなり苦戦した記憶なので笑
> 
> 
> 
> 例えばですが、Opponent Team Label に widthを設定していますが設定する恩恵は特になさそうです。
> 
> 理由は相手チームによってラベルのwidthが可変になるからです！

少し考えます！
今日中にどっちか決めたいと思います！

2020-11-12 09:28 UTC, hidec-7 commented
> あとcommitですが、自分が見る限り特に名称に問題はないです！
> 
> 
> 
> まあファイル名はできればさけた方がレビューした人がどこを修正したのかがわかるかなって程度です！
> 
> 
> 
> あと自分がcommitは細かい方がいい！ってアドバイスしておいて申し訳ないですが、
> 
> もう少しcommitをするタイミングに粒度がもう少し粗くてもいいかと思いました！mm

了解しました！

2020-11-12 09:28 UTC, hidec-7 commented
> あとこれも聞き流すレベルで大丈夫ですが、レイアウトの制約は8の倍数で設定するときれいに見えるって聞いたことがあります

そうなんですね！
参考にします！

2020-11-12 12:21 UTC, fuchi0741 commented
> > 若干意地悪かもしれませんがSE(第一世代)で見るとレイアウトが崩れてしまっていますね、、、。
> > <img alt="スクリーンショット 2020-11-12 17 46 53" width="377" src="https://user-images.githubusercontent.com/50318372/98916927-1743f980-250f-11eb-9cb8-3223f819dce4.png">
> 
> あれ、自分で見たとき崩れてないと思ったんですけど違うのをビルドして見てたんですね笑

たぶん第二世代の方のSEでみていたのかと！
初代と大きさが違うんですよね笑

2020-11-12 13:41 UTC, hidec-7 commented
> > > 若干意地悪かもしれませんがSE(第一世代)で見るとレイアウトが崩れてしまっていますね、、、。
> 
> > > <img alt="スクリーンショット 2020-11-12 17 46 53" width="377" src="https://user-images.githubusercontent.com/50318372/98916927-1743f980-250f-11eb-9cb8-3223f819dce4.png">
> 
> > 
> 
> > あれ、自分で見たとき崩れてないと思ったんですけど違うのをビルドして見てたんですね笑
> 
> 
> 
> たぶん第二世代の方のSEでみていたのかと！
> 
> 初代と大きさが違うんですよね笑

なるほどです！笑
そこまで見てなかったです笑

2020-11-15 02:52 UTC, fuchi0741 commented
一旦こんな感じですかね

<img width="1194" alt="スクリーンショット 2020-11-15 11 50 54" src="https://user-images.githubusercontent.com/50318372/99161778-dc250e80-2738-11eb-89d3-767fc98d6479.png">

2020-11-15 02:54 UTC, hidec-7 commented
> 一旦こんな感じですかね
> 
> 
> 
> <img width="1194" alt="スクリーンショット 2020-11-15 11 50 54" src="https://user-images.githubusercontent.com/50318372/99161778-dc250e80-2738-11eb-89d3-767fc98d6479.png">
> 
> 

めっちゃいい感じです！

2020-11-15 12:33 UTC, hidec-7 commented
AutoLayout修正しました！
こんな感じでいいですかね？
機種はSE(1st)まで確認して崩れはなくなりました。

2020-11-17 06:10 UTC, fuchi0741 reviewed
@hidec-7 

すいません。返信遅れました！

レイアウトはめっちゃいい感じです！
飲み込み早くてビックリしています笑

2020-11-17 06:11 UTC, fuchi0741 requested changes
コンフリクトの解消をお願いします
それが完了できたらapprove出しますmm

ちょっと難しそうだったら質問ください！

2020-11-17 06:12 UTC, fuchi0741 reviewed
あとは単純な疑問なのですが、UIを青に変更した理由をお聞きしてもよろしいですか??
(興味本位で聞いているだけですmm)

2020-11-17 06:19 UTC, hidec-7 commented
> @hidec-7
> 
> すいません。返信遅れました！
> 
> レイアウトはめっちゃいい感じです！
> 飲み込み早くてビックリしています笑

ありがとうございます！
よかったです！笑

2020-11-17 06:19 UTC, hidec-7 commented
> コンフリクトの解消をお願いします
> それが完了できたらapprove出しますmm
> 
> ちょっと難しそうだったら質問ください！

やってみます！

2020-11-17 06:22 UTC, hidec-7 commented
> あとは単純な疑問なのですが、UIを青に変更した理由をお聞きしてもよろしいですか??
> (興味本位で聞いているだけですmm)

何となくですが、文字等全て黒にしていて、ボケーっとUIどうかなーとか考えていて、もう少し変化が欲しい気がするなと思って青にしてみました。試してみたら何気なく見やすくなった気がしたのでいいかなと笑

2020-11-17 06:28 UTC, fuchi0741 commented
> > あとは単純な疑問なのですが、UIを青に変更した理由をお聞きしてもよろしいですか??
> > (興味本位で聞いているだけですmm)
> 
> 何となくですが、文字等全て黒にしていて、ボケーっとUIどうかなーとか考えていて、もう少し変化が欲しい気がするなと思って青にしてみました。試してみたら何気なく見やすくなった気がしたのでいいかなと笑

これ知っておくといいですが、
UIが青いとユーザーは無意識にボタンだと思う傾向があります。
つまり、青い部分をタップすると何か変化することをユーザーは期待します。

ただ、今回はLabelを青くしているので当然押しても何も変化がなくユーザーの期待を裏切りUXの低下を招く恐れがあるなーって見ていて思いましたmm

2020-11-17 06:36 UTC, hidec-7 commented
> > > あとは単純な疑問なのですが、UIを青に変更した理由をお聞きしてもよろしいですか??
> > > (興味本位で聞いているだけですmm)
> > 
> > 
> > 何となくですが、文字等全て黒にしていて、ボケーっとUIどうかなーとか考えていて、もう少し変化が欲しい気がするなと思って青にしてみました。試してみたら何気なく見やすくなった気がしたのでいいかなと笑
> 
> ありがとうございます！
> 
> これ知っておくといいですが、
> UIが青いとユーザーは無意識にボタンだと思う傾向があります。
> つまり、青い部分をタップすると何か変化することをユーザーは期待します。
> 
> ただ、今回はLabelを青くしているので当然押しても何も変化がなくユーザーの期待を裏切りUXの低下を招く恐れがあるなーって見ていて思いましたmm

なるほどです！

それを考えると黒に戻す方がいいと思うので戻します！

2020-11-17 06:37 UTC, hidec-7 commented
コンフリクト解消やって見たのですができていますか？

2020-11-17 06:41 UTC, hidec-7 commented
あれ、なんかやらかしてしまった気がするのですが。

2020-11-18 16:11 UTC, fuchi0741 commented
PRクローズお願いしますーー

2020-11-19 04:23 UTC, closed without merging