試合管理画面->
hidec-7/MySoccerNoteApp pull request #13
Opened 2020-11-14 09:10 UTC by hidec-7

**clone コマンド**
git clone -b feature/add-UI-GameRegister-ViewController https://github.com/hidec-7/SoccerNoteDev.git

**Trello**
試合登録画面 ViewController 実装

**概要**
試合登録画面のViewControllerを実装しました。
試合登録画面のファイルを作成し、紐付けまでしました。
試合管理画面と試合登録画面の紐付けもしました。

**レビューで見て欲しいポイント**
実装方法に問題はないか。

**レビュー依頼**
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741

2020-11-14 09:16 UTC, fuchi0741 requested changes
@hidec-7 コメントしましたー！

2020-11-14 09:16 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
余計なスペースなので削除推奨でっす！

2020-11-14 09:16 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +        self.navigationController?.navigationBar.tintColor = UIColor.white
これらはタイトルのプロパティを変更すると言う意味で共通なので、メソッド化することで可読性が上がると思いました！

2020-11-14 09:16 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> -    */
👍

2020-11-14 09:22 UTC, fuchi0741 commented
> 画面遷移とNavigationのUI変更を違うブランチでやろうと思っていたんですけど、一緒にしてしまいました。
> レビューしづらかったらすいません。
👍

2020-11-14 09:23 UTC, hidec-7 commented on SoccerNoteApp/GameRegisterViewController.swift
了解です！

2020-11-14 09:24 UTC, hidec-7 commented on SoccerNoteApp/GameRegisterViewController.swift
> +        self.navigationController?.navigationBar.tintColor = UIColor.white
なるほどです！
やってみます！

2020-11-14 09:40 UTC, hidec-7 commented
修正しました！
これで良いですかね？

2020-11-14 13:16 UTC, fuchi0741 requested changes
@hidec-7 コメントしましたー！

2020-11-14 13:16 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +        self.navigationController?.navigationBar.tintColor = UIColor.white
メソッドの命名があまりよろしくないかもです！

NavigationBar()だとNavigationBarをどうしているかメソッドの中身を見ない限りわからないです！
なので、命名を変更すると可読性が上がっていいコードになると思いますよ！

自分だったらsetupNavigationBarとかにしますね！

あとはメソッドの最初は原則小文字ですね！

2020-11-14 14:09 UTC, hidec-7 commented on SoccerNoteApp/GameRegisterViewController.swift
> +        self.navigationController?.navigationBar.tintColor = UIColor.white
なるほどです！
最初の文字小文字、忘れてました笑

修正します！

2020-11-14 16:44 UTC, hidec-7 commented
メソッド名修正しました！
ふちさんの命名にさせていただきました！笑

2020-11-15 01:17 UTC, fuchi0741 approved these changes
@hidec-7 LGTM👍

2020-11-15 02:50 UTC, merged