試合登録画面　StackView実装
hidec-7/MySoccerNoteApp pull request #16
Opened 2020-11-17 04:59 UTC by hidec-7

**clone コマンド**
git clone -b feature/add-UI-StackView https://github.com/hidec-7/SoccerNoteDev.git

**Trello**
試合登録画面 チーム・スコア: StackView(TextField, Label) 実装

**概要**
試合登録画面のチーム・スコアのUIにStackViewを実装し、その中にTextFeildとLabelを実装しました。
キーボードをカスタマイズし、Return or 画面タップでキーボードを閉じる実装とスコアのキーボードを数字のみにする実装をしました。

**レビューで見て欲しいポイント**
AutoLayoutでUI的に問題ないか。
AutoLayoutの制約方法に問題ないか。
もう少しこうした方がいいと言ったアドバイスあれば頂きたいです。

**実機build/期待通りの挙動をするか**
OK

※UI変更した場合のみ記述

**11 Pro や SE など大きさが異なる端末のレイアウトが崩れていないか？**
OK

**レビュー依頼**
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741

**補足**
ここでは関係ないのですが、実機ビルドした時にダークモード非対応がやっぱりできていませんでした。笑
また後々に修正したいと思います。

2020-11-17 06:13 UTC, fuchi0741 commented
> 実機ビルドした時にダークモード非対応がやっぱりできていませんでした。笑
> また後々に修正したいと思います。

なんでですかねmm
了解です！！

2020-11-17 06:16 UTC, fuchi0741 commented
軽く見たのですが、ガッツリレビューしたいので少々お待ちください。

なので一旦コンフリクト解消に尽力してくださいmm

2020-11-17 06:23 UTC, hidec-7 commented
> 軽く見たのですが、ガッツリレビューしたいので少々お待ちください。
> 
> なので一旦コンフリクト解消に尽力してくださいmm

了解しました！

2020-11-18 16:04 UTC, fuchi0741 reviewed
@hidec-7 stackViewの使い方はすごくいいと思います！！

質問ですが、
9:2 の比率は一見不要のように見えたのですが、必要性はありますか？

<img width="343" alt="スクリーンショット 2020-11-19 1 02 50" src="https://user-images.githubusercontent.com/50318372/99554902-10335480-2a03-11eb-8a52-48d40fa1621c.png">

2020-11-18 16:07 UTC, fuchi0741 reviewed
左右に24 と center x はこの場合同じなので center x は削除してもいいかも知れないです！

<img width="257" alt="スクリーンショット 2020-11-19 1 04 55" src="https://user-images.githubusercontent.com/50318372/99555082-41ac2000-2a03-11eb-98c4-c87aea28a615.png">

2020-11-18 16:09 UTC, fuchi0741 commented
自分だったら、このように制約をつけます！
参考にしてみてください！
わからないところがあれば聞いてください！

<img width="269" alt="スクリーンショット 2020-11-19 1 07 33" src="https://user-images.githubusercontent.com/50318372/99555402-9cde1280-2a03-11eb-8496-d6698e2fadaf.png">

2020-11-18 16:10 UTC, fuchi0741 commented
@hidec-7 コメントしましたー！

2020-11-19 04:28 UTC, hidec-7 commented
> @hidec-7 stackViewの使い方はすごくいいと思います！！
> 
> 質問ですが、
> 9:2 の比率は一見不要のように見えたのですが、必要性はありますか？
> 
> <img alt="スクリーンショット 2020-11-19 1 02 50" width="343" src="https://user-images.githubusercontent.com/50318372/99554902-10335480-2a03-11eb-8a52-48d40fa1621c.png">

StackViewの高さが決まっていないので、必要かなと思ったんですけど、幅は決まっているしいずれ下に前半後半まとめとか実装した時に高さも決まるから必要ないかなと指摘いただいて思いました

2020-11-19 04:28 UTC, hidec-7 commented
> 左右に24 と center x はこの場合同じなので center x は削除してもいいかも知れないです！
> 
> <img alt="スクリーンショット 2020-11-19 1 04 55" width="257" src="https://user-images.githubusercontent.com/50318372/99555082-41ac2000-2a03-11eb-98c4-c87aea28a615.png">

ほんとですね！

2020-11-19 04:30 UTC, hidec-7 commented
> 自分だったら、このように制約をつけます！
> 参考にしてみてください！
> わからないところがあれば聞いてください！
> 
> <img alt="スクリーンショット 2020-11-19 1 07 33" width="269" src="https://user-images.githubusercontent.com/50318372/99555402-9cde1280-2a03-11eb-8496-d6698e2fadaf.png">

なるほどです！
あのPropotionalWithって言うのが使ったことがなくてわからないです。
どう言った制約になるんですか？

2020-11-19 06:33 UTC, hidec-7 commented
> @hidec-7 stackViewの使い方はすごくいいと思います！！
> 
> 質問ですが、
> 9:2 の比率は一見不要のように見えたのですが、必要性はありますか？
> 
> <img alt="スクリーンショット 2020-11-19 1 02 50" width="343" src="https://user-images.githubusercontent.com/50318372/99554902-10335480-2a03-11eb-8a52-48d40fa1621c.png">

比率消して見たのですが、不要だと思うので消します！

2020-11-19 06:37 UTC, hidec-7 commented
> 自分だったら、このように制約をつけます！
> 参考にしてみてください！
> わからないところがあれば聞いてください！
> 
> <img alt="スクリーンショット 2020-11-19 1 07 33" width="269" src="https://user-images.githubusercontent.com/50318372/99555402-9cde1280-2a03-11eb-8496-d6698e2fadaf.png">

理解しました！この制約の付け方がいいので変更します！

2020-11-19 15:46 UTC, fuchi0741 reviewed
試合の一覧画面から登録画面に行く時はスライドで画面遷移をしていると思いますが、何か意図はありますでしょうか？

というのも登録だったり修正だったりユーザーが何かを記入する時はモーダル遷移で表すのが一般的なので気になりました、、、！

2020-11-19 15:51 UTC, fuchi0741 reviewed
stackViewって名前だと一見なんのstackViewかわからないので名前をつけてあげるとわかりやすくなると思いました！

<img width="278" alt="スクリーンショット 2020-11-20 0 50 19" src="https://user-images.githubusercontent.com/50318372/99689467-60c1b500-2aca-11eb-80be-f8c021e88591.png">

2020-11-19 15:58 UTC, fuchi0741 requested changes

2020-11-19 15:58 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +        self.opponentScoreLabel.keyboardType = UIKeyboardType.numberPad
ここ2つはメソッド化してまとめることができるので修正お願いしますー！

2020-11-19 15:58 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +        self.opponentScoreLabel.keyboardType = UIKeyboardType.numberPad
あとちょっと応用ですが、使用するキーボードをenumを使用してまとめると
どんなキーボードをアプリで使用するのかコードでわかるのでいいと思いました！

修正するかは任せますmm

2020-11-19 15:58 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    @IBOutlet weak var opponentScoreLabel: UITextField!
命名がNGですね！
UITextFieldを命名するときは「xxxTextField」という命名にしましょう！

「xxxLabel」だとUILabelだと無意識に思ってしまいますー！

19行目見て、labelにデリゲートメソッドあったっけ？と混乱しました笑

2020-11-19 16:00 UTC, fuchi0741 commented
> > 自分だったら、このように制約をつけます！
> > 参考にしてみてください！
> > わからないところがあれば聞いてください！
> > <img alt="スクリーンショット 2020-11-19 1 07 33" width="269" src="https://user-images.githubusercontent.com/50318372/99555402-9cde1280-2a03-11eb-8496-d6698e2fadaf.png">
> 
> 理解しました！この制約の付け方がいいので変更します！

比率は大きく2つあるので知っておくといいですね！
1) UIの縦横の比率
2)UI と 親のView との比率 (今回はこっち)

2020-11-19 16:02 UTC, fuchi0741 reviewed
@hidec-7 コメントしましたー！
レイアウトは問題なく、いいと思います！
他が修正点あるので、修正お願いしますー！

2020-11-20 01:23 UTC, hidec-7 commented
> 試合の一覧画面から登録画面に行く時はスライドで画面遷移をしていると思いますが、何か意図はありますでしょうか？
> 
> というのも登録だったり修正だったりユーザーが何かを記入する時はモーダル遷移で表すのが一般的なので気になりました、、、！
> 
> (すいません。これ別ブランチで対応していただいていたと思うのですが気づけませんでした)

少し迷った部分では、あるんですけどこのアプリを作るのに見本にしていたアプリがあって、それがスライド遷移だったと言うのと、自分的にもしっくりくるなと思いました。笑

2020-11-20 01:23 UTC, hidec-7 commented
> stackViewって名前だと一見なんのstackViewかわからないので名前をつけてあげるとわかりやすくなると思いました！
> 
> <img alt="スクリーンショット 2020-11-20 0 50 19" width="278" src="https://user-images.githubusercontent.com/50318372/99689467-60c1b500-2aca-11eb-80be-f8c021e88591.png">

この3つのStackViewそれぞれにですかね？

2020-11-20 01:28 UTC, hidec-7 commented on SoccerNoteApp/GameRegisterViewController.swift
> +        self.opponentScoreLabel.keyboardType = UIKeyboardType.numberPad
> 23-2４行目の2つはメソッド化してまとめることができるので修正お願いしますー！

了解です！

2020-11-20 01:34 UTC, hidec-7 commented on SoccerNoteApp/GameRegisterViewController.swift
> +        self.opponentScoreLabel.keyboardType = UIKeyboardType.numberPad
> あとちょっと応用ですが、使用するキーボードをenumを使用してまとめると
> どんなキーボードをアプリで使用するのかコードでわかるのでいいと思いました！
> 
> 修正するかは任せますmm

enum使ったことがなくて少し調べて見たのですが、ちょっとすぐにはできそうになかったのでまた時間ある時に勉強してみようと思います！

2020-11-20 01:35 UTC, hidec-7 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    @IBOutlet weak var opponentScoreLabel: UITextField!
> 命名がNGですね！
> UITextFieldを命名するときは「xxxTextField」という命名にしましょう！
> 
> 「xxxLabel」だとUILabelだと無意識に思ってしまいますー！
> 
> 19行目見て、labelにデリゲートメソッドあったっけ？と混乱しました笑

ほんとですね！！
自分でもなぜLabelにしたのか、、、笑
修正します！

2020-11-20 01:36 UTC, hidec-7 commented
> > > 自分だったら、このように制約をつけます！
> > > 参考にしてみてください！
> > > わからないところがあれば聞いてください！
> > > <img alt="スクリーンショット 2020-11-19 1 07 33" width="269" src="https://user-images.githubusercontent.com/50318372/99555402-9cde1280-2a03-11eb-8496-d6698e2fadaf.png">
> > 
> > 
> > 理解しました！この制約の付け方がいいので変更します！
> 
> 比率は大きく2つあるので知っておくといいですね！
> 
> 1. UIの縦横の比率
> 2. UI と 親のView との比率 (今回はこっち)

はい！
ありがとうございます！

2020-11-20 01:56 UTC, hidec-7 commented
修正しました！
StackViewの命名なんですけど、こんな感じでどうですかね？

2020-11-20 02:39 UTC, hidec-7 commented
> 修正しました！
> StackViewの命名なんですけど、こんな感じでどうですかね？

![image](https://user-images.githubusercontent.com/66632738/99751167-01dd5980-2b25-11eb-80f7-facd48fad592.png)

2020-11-20 16:59 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +        self.opponentScoreLabel.keyboardType = UIKeyboardType.numberPad
@hidec-7 enumを後ほど対応予定ならチケット作成お願いしますー！

2020-11-20 17:02 UTC, fuchi0741 commented
> > 試合の一覧画面から登録画面に行く時はスライドで画面遷移をしていると思いますが、何か意図はありますでしょうか？
> > というのも登録だったり修正だったりユーザーが何かを記入する時はモーダル遷移で表すのが一般的なので気になりました、、、！
> > (すいません。これ別ブランチで対応していただいていたと思うのですが気づけませんでした)
> 
> 少し迷った部分では、あるんですけどこのアプリを作るのに見本にしていたアプリがあって、それがスライド遷移だったと言うのと、自分的にもしっくりくるなと思いました。笑

見本のアプリを教えていただいても大丈夫ですか？
自分的にはこのケースだとモーダル遷移一択なので、、、、、

2020-11-20 17:09 UTC, fuchi0741 commented
一旦Human Interface Guidelinesを共有しますね。

モーダル遷移
https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/modality/

ナビゲーション
https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/navigation/

2020-11-20 17:18 UTC, fuchi0741 reviewed
細かいですが、このスタックビューも命名があるとより良いです！

なんで命名するかと言うと、stackViewだけだとどこのUIを指しているのがパッと見わからないです。

stackiViewをクリックして細部をみてやっとわかるのでいいっちゃいいですが、それが積み重なるとコードや仕様を把握するのに時間がかかってしまいます、、！

なのでパッとみで何を表すstackViewかがわかるのが理想です。

<img width="218" alt="スクリーンショット 2020-11-21 2 14 32" src="https://user-images.githubusercontent.com/50318372/99829198-51606b80-2b9f-11eb-92fe-1d28fb2ee37d.png">

2020-11-20 17:20 UTC, fuchi0741 reviewed
@hidec-7 コメントしましたー！

2020-11-21 02:32 UTC, hidec-7 commented
> > > 試合の一覧画面から登録画面に行く時はスライドで画面遷移をしていると思いますが、何か意図はありますでしょうか？
> 
> > > というのも登録だったり修正だったりユーザーが何かを記入する時はモーダル遷移で表すのが一般的なので気になりました、、、！
> 
> > > (すいません。これ別ブランチで対応していただいていたと思うのですが気づけませんでした)
> 
> > 
> 
> > 少し迷った部分では、あるんですけどこのアプリを作るのに見本にしていたアプリがあって、それがスライド遷移だったと言うのと、自分的にもしっくりくるなと思いました。笑
> 
> 
> 
> 見本のアプリを教えていただいても大丈夫ですか？
> 
> また、何かしらの参考になる記事があれば、共有お願いします、、！
> 
> 自分的にはこのケースだとモーダル遷移一択なので、、、、、
> 
> 
> 
> 登録ボタンを押したあとの挙動はどんなイメージですか？
> 
> 登録ボタンを押したあとにモーダルビューを外すのが綺麗かと思いましたがいかがでしょうか？
> 
> 

https://apps.apple.com/jp/app/%E3%82%B5%E3%83%83%E3%82%AB%E3%83%BC%E6%89%8B%E5%B8%B3/id953499261
こちらです！
了解しました！

登録ボタンを押したあと、試合管理画面に遷移する。です。

モーダル遷移でも全然いいと思います！

一つ気になるのが、モーダルだと画面の縦のサイズが少し小さくなってしまうのかなって感じです

2020-11-21 02:33 UTC, hidec-7 commented
> 一旦Human Interface Guidelinesを共有しますね。
> 
> 
> 
> モーダル遷移
> 
> https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/modality/
> 
> 
> 
> ナビゲーション
> 
> https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/navigation/
> 
> 

ありがとうございます！

2020-11-21 02:33 UTC, hidec-7 commented
> 細かいですが、このスタックビューも命名があるとより良いです！
> 
> 
> 
> なんで命名するかと言うと、stackViewだけだとどこのUIを指しているのがパッと見わからないです。
> 
> 
> 
> stackiViewをクリックして細部をみてやっとわかるのでいいっちゃいいですが、それが積み重なるとコードや仕様を把握するのに時間がかかってしまいます、、！
> 
> 
> 
> なのでパッとみで何を表すstackViewかがわかるのが理想です。
> 
> 
> 
> <img width="218" alt="スクリーンショット 2020-11-21 2 14 32" src="https://user-images.githubusercontent.com/50318372/99829198-51606b80-2b9f-11eb-92fe-1d28fb2ee37d.png">
> 
> 

なるほどです！

了解しました！！

修正します！

2020-11-21 05:11 UTC, fuchi0741 commented
> > > 試合の一覧画面から登録画面に行く時はスライドで画面遷移をしていると思いますが、何か意図はありますでしょうか？
> > > というのも登録だったり修正だったりユーザーが何かを記入する時はモーダル遷移で表すのが一般的なので気になりました、、、！
> > > (すいません。これ別ブランチで対応していただいていたと思うのですが気づけませんでした)
> > 
> > 
> > 少し迷った部分では、あるんですけどこのアプリを作るのに見本にしていたアプリがあって、それがスライド遷移だったと言うのと、自分的にもしっくりくるなと思いました。笑
> 
> 見本のアプリを教えていただいても大丈夫ですか？
> また、何かしらの参考になる記事があれば、共有お願いします、、！
> 自分的にはこのケースだとモーダル遷移一択なので、、、、、
> 
> 登録ボタンを押したあとの挙動はどんなイメージですか？
> 登録ボタンを押したあとにモーダルビューを外すのが綺麗かと思いましたがいかがでしょうか？

2020-11-21 05:14 UTC, fuchi0741 commented
> > > > 試合の一覧画面から登録画面に行く時はスライドで画面遷移をしていると思いますが、何か意図はありますでしょうか？
> > 
> > 
> > > > というのも登録だったり修正だったりユーザーが何かを記入する時はモーダル遷移で表すのが一般的なので気になりました、、、！
> > 
> > 
> > > > (すいません。これ別ブランチで対応していただいていたと思うのですが気づけませんでした)
> > 
> > 
> > > 
> > 
> > 
> > > 少し迷った部分では、あるんですけどこのアプリを作るのに見本にしていたアプリがあって、それがスライド遷移だったと言うのと、自分的にもしっくりくるなと思いました。笑
> > 
> > 
> > 見本のアプリを教えていただいても大丈夫ですか？
> > また、何かしらの参考になる記事があれば、共有お願いします、、！
> > 自分的にはこのケースだとモーダル遷移一択なので、、、、、
> > 登録ボタンを押したあとの挙動はどんなイメージですか？
> > 登録ボタンを押したあとにモーダルビューを外すのが綺麗かと思いましたがいかがでしょうか？
> 
> https://apps.apple.com/jp/app/%E3%82%B5%E3%83%83%E3%82%AB%E3%83%BC%E6%89%8B%E5%B8%B3/id953499261
> こちらです！
> 了解しました！
> 
> 登録ボタンを押したあと、試合管理画面に遷移する。です。
> 
> モーダル遷移でも全然いいと思います！
> 
> 一つ気になるのが、モーダルだと画面の縦のサイズが少し小さくなってしまうのかなって感じです

ありがとうございます！
教えていただいたアプリめっちゃ今作ろうとしているやつと似ていますね笑

モーダル遷移でもフルスクリーンに設定する方法があるので、それを使用すれば問題ないと思います！

あとはヒデトさんのアプリなので、モーダル遷移でもスライドでも任せます!
もし変更するなら別チケットにて対応お願いしますmm

2020-11-21 05:28 UTC, hidec-7 commented
> > > > > 試合の一覧画面から登録画面に行く時はスライドで画面遷移をしていると思いますが、何か意図はありますでしょうか？
> > > 
> > > 
> > > > > というのも登録だったり修正だったりユーザーが何かを記入する時はモーダル遷移で表すのが一般的なので気になりました、、、！
> > > 
> > > 
> > > > > (すいません。これ別ブランチで対応していただいていたと思うのですが気づけませんでした)
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 少し迷った部分では、あるんですけどこのアプリを作るのに見本にしていたアプリがあって、それがスライド遷移だったと言うのと、自分的にもしっくりくるなと思いました。笑
> > > 
> > > 
> > > 見本のアプリを教えていただいても大丈夫ですか？
> > > また、何かしらの参考になる記事があれば、共有お願いします、、！
> > > 自分的にはこのケースだとモーダル遷移一択なので、、、、、
> > > 登録ボタンを押したあとの挙動はどんなイメージですか？
> > > 登録ボタンを押したあとにモーダルビューを外すのが綺麗かと思いましたがいかがでしょうか？
> > 
> > 
> > https://apps.apple.com/jp/app/%E3%82%B5%E3%83%83%E3%82%AB%E3%83%BC%E6%89%8B%E5%B8%B3/id953499261
> > こちらです！
> > 了解しました！
> > 登録ボタンを押したあと、試合管理画面に遷移する。です。
> > モーダル遷移でも全然いいと思います！
> > 一つ気になるのが、モーダルだと画面の縦のサイズが少し小さくなってしまうのかなって感じです
> 
> ありがとうございます！
> 教えていただいたアプリめっちゃ今作ろうとしているやつと似ていますね笑
> 
> モーダル遷移でもフルスクリーンに設定する方法があるので、それを使用すれば問題ないと思います！
> 
> あとはヒデトさんのアプリなので、モーダル遷移でもスライドでも任せます!
> もし変更するなら別チケットにて対応お願いしますmm

似ちゃってます笑

なるほどです！
モーダルに変更しようと思います！

また別でやります！

2020-11-21 05:38 UTC, hidec-7 commented
StackView命名しました！

2020-11-21 06:22 UTC, fuchi0741 approved these changes
@hidec-7 LGTM👍
お疲れ様でした！！

2020-11-21 08:25 UTC, merged