Feature/add ui table view cell
hidec-7/MySoccerNoteApp pull request #17
Opened 2020-11-19 07:19 UTC by hidec-7

**clone コマンド**

**Trello**
該当のTrelloのチケットの名称を共有

**概要**
このPRの概要を記述してください

**レビューで見て欲しいポイント**
レビューで特に見て欲しい観点を記述してください

**参考URL**
レビューをする時に参考になるURLを共有してください

**実機build/期待通りの挙動をするか**
OK / NG

※UI変更した場合のみ記述

**11 Pro や SE など大きさが異なる端末のレイアウトが崩れていないか？**
OK / NG

**レビュー依頼**
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741

**補足**

2020-11-19 16:06 UTC, fuchi0741 requested changes
@hidec-7 
余計な差分が大量にあるので、ひとまずその修正をお願いしますー！
コンフリクト時に出てきたコメントが残っちゃっていますー！

2020-11-19 16:06 UTC, fuchi0741 commented on SoccerNoteApp/GameManagementViewController.swift
> +>>>>>>> origin/feature/add-UI-TableViewCell
余計な差分なので削除お願いします

2020-11-19 16:06 UTC, fuchi0741 commented on SoccerNoteApp.xcodeproj/project.pbxproj
> +>>>>>>> origin/feature/add-UI-TableViewCell
余計な差分を無くしてくださいー！

2020-11-19 16:06 UTC, fuchi0741 commented on SoccerNoteApp.xcodeproj/project.pbxproj
> +>>>>>>> origin/feature/add-UI-TableViewCell
余計な差分は削除お願いしますー

2020-11-19 16:06 UTC, fuchi0741 commented on SoccerNoteApp/GameManagementTableViewCell.xib
> +<<<<<<< HEAD
余計な差分

2020-11-19 16:06 UTC, fuchi0741 commented on SoccerNoteApp/GameManagementTableViewCell.xib
> +=======
余計な差分

2020-11-19 16:06 UTC, fuchi0741 commented on SoccerNoteApp/GameManagementTableViewCell.xib
> +<<<<<<< HEAD
余計な差分

2020-11-19 16:06 UTC, fuchi0741 commented on SoccerNoteApp/GameManagementTableViewCell.xib
> +=======
同じ

2020-11-20 01:11 UTC, hidec-7 commented
> @hidec-7
> 余計な差分が大量にあるので、ひとまずその修正をお願いしますー！
> コンフリクト時に出てきたコメントが残っちゃっていますー！

修正しましたー！

2020-11-20 16:56 UTC, fuchi0741 reviewed
`SoccerNoteApp/GameManagementTableViewCell.xib`
がないためレビューができないです！
修正お願いします！

該当ファイルのパスを確認してみるといいと思います！
多分該当ファイルだけ別の場所にあるのではと思いますー

2020-11-20 16:57 UTC, fuchi0741 reviewed
@hidec-7 コメントしましたー！
コンフリクトの解消はGoodですー！

2020-11-21 05:52 UTC, hidec-7 commented
> `SoccerNoteApp/GameManagementTableViewCell.xib`
> がないためレビューができないです！
> 修正お願いします！
> 
> 該当ファイルのパスを確認してみるといいと思います！
> 多分該当ファイルだけ別の場所にあるのではと思いますー

ごめんなさい、調べて見たりいろいろ触って見たりしたのですがどう言うことなのかわかりません。
`SoccerNoteApp/GameManagementTableViewCell.xib`
がないと言うのはどこになのか、別の場所とはどう言うことなのかわからないです。
すいません。

2020-11-21 05:52 UTC, hidec-7 commented
> @hidec-7 コメントしましたー！
> コンフリクトの解消はGoodですー！

ありがとうございます！

2020-11-21 06:37 UTC, fuchi0741 commented
> > `SoccerNoteApp/GameManagementTableViewCell.xib`
> > が
> > 修正お願いします！
> > 該当ファイルのパスを確認してみるといいと思います！
> > 多分該当ファイルだけ別の場所にあるのではと思いますー
> 
> ごめんなさい、調べて見たりいろいろ触って見たりしたのですがどう言うことなのかわかりません。
> `SoccerNoteApp/GameManagementTableViewCell.xib`
> がないと言うのはどこになのか、別の場所とはどう言うことなのかわからないです。
> すいません。



<img width="265" alt="スクリーンショット 2020-11-21 15 26 44" src="https://user-images.githubusercontent.com/50318372/99869485-ac7d7700-2c0e-11eb-9ce0-d9babfe5a41d.png">

@hidec-7 
ここにファイルごとの位置がわかるので、他と違うか確認してみてください！

2020-11-21 08:28 UTC, hidec-7 commented
> > > `SoccerNoteApp/GameManagementTableViewCell.xib`
> > > が
> > > 修正お願いします！
> > > 該当ファイルのパスを確認してみるといいと思います！
> > > 多分該当ファイルだけ別の場所にあるのではと思いますー
> > 
> > 
> > ごめんなさい、調べて見たりいろいろ触って見たりしたのですがどう言うことなのかわかりません。
> > `SoccerNoteApp/GameManagementTableViewCell.xib`
> > がないと言うのはどこになのか、別の場所とはどう言うことなのかわからないです。
> > すいません。
> 
> <img alt="スクリーンショット 2020-11-21 15 26 44" width="265" src="https://user-images.githubusercontent.com/50318372/99869485-ac7d7700-2c0e-11eb-9ce0-d9babfe5a41d.png">
> 
> @hidec-7
> ここにファイルごとの位置がわかるので、他と違うか確認してみてください！

![image](https://user-images.githubusercontent.com/66632738/99871534-ee161e00-2c1e-11eb-85fb-5ffd84897eed.png)

他のファイルと比べて見たのですが、同じだと思います。

2020-11-21 09:58 UTC, closed without merging