モーダル遷移に変更
hidec-7/MySoccerNoteApp pull request #20
Opened 2020-11-22 23:55 UTC by hidec-7

**clone コマンド**
git clone -b feature/modification-screentransition https://github.com/hidec-7/SoccerNoteDev.git

**Trello**
試合管理画面→試合登録画面　モーダル遷移に変更

**概要**
試合管理画面から試合登録画面への遷移をモーダル遷移に変更。
試合登録画面にナビゲーションバーを実装し、戻る遷移の時に必要なBackボタンを実装。

**レビューで見て欲しいポイント**
モーダル遷移の実装方法に問題はないか。
ナビゲーションバーを実装するに当たってAutoLayoutを少し修正したので、そのAutoLayoutに問題はないか。

**実機build/期待通りの挙動をするか**
OK

※UI変更した場合のみ記述

**11 Pro や SE など大きさが異なる端末のレイアウトが崩れていないか？**
OK

**レビュー依頼**
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741

2020-11-23 13:14 UTC, fuchi0741 requested changes
@hidec-7 軽微な修正ですが、お願いしますー！

レイアウトとかは問題ないと思いました！

2020-11-23 13:14 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +
ここはdelegate関連のがまとまっているとわかるので、L25のスペースは不要な気がします。

2020-11-23 13:14 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    @IBAction func backToGameManagement(_ sender: Any) {
outlet と action は1行スペースがあった方がわかりやすいです！

2020-11-23 13:14 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    @IBAction func backToGameManagement(_ sender: Any) {
あとoutletは1箇所にまとめて記述すると見やすくなると思いました！

outlet
outlet
outlet

action

みたいなイメージしてますmm

2020-11-23 13:59 UTC, hidec-7 commented on SoccerNoteApp/GameRegisterViewController.swift
> +
了解しました！

2020-11-23 14:00 UTC, hidec-7 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    @IBAction func backToGameManagement(_ sender: Any) {
なるほどです！！
修正します！

2020-11-23 17:13 UTC, fuchi0741 requested changes
@hidec-7 少々細かいですが、修正依頼出しました！
1回目に気づけずすいませんーー!

2020-11-23 17:13 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    }
1点追加で修正依頼です！
基本的に型は指定を依頼したいですー
(Anyはほぼ型の指定なしとほぼ同義です！)

型指定して欲しい理由として2つあるので、共有です。

1) Swiftは型指定をしっかりしている静的言語

2) 型を指定しないとどんなメソッドか想像しづらい
→例えばbackToGameManagement(_ sender: Any)だと型がわからず、
storyboardを見て、型がBarButtonItemだとわかりボタンをタップした時の処理だと理解できました！
ただ、storyboardを見ると言う手間が少々面倒くさいです。
そういった手順が多くなると、コードの可読性がどんどん下がってしまいます。

それを解決するために型を指定する方法です！

backToGameManagement(_ sender: UIButton)
↑例えばこれだと一瞬でボタンに押した時のメソッドだと理解できるのでコードを読むハードルがめっちゃ下がります！
また、型指定されているのでSwiftっぽいです！

2020-11-23 17:14 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    }
ただ、Swiftには型推論って物があるので型が明確にわかる場合は型指定しなくていいです！

といっても最初はわからないと思うので全てに型をつけるくらいの意識でいいかなって思います。

2020-11-23 17:19 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +
了解しました！レベルであれば今後はスタンプのみで大丈夫ですよ!

2020-11-23 17:21 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    @IBAction func backToGameManagement(_ sender: Any) {
修正が終わった後に修正した旨のコメントをいただけるとスムーズにレビューできると思いました！
(通知 = レビューに極力したいです、、！)

2020-11-23 17:30 UTC, fuchi0741 requested changes

2020-11-23 17:30 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
L30のスペースは余分なので削除したいですmm

2020-11-24 07:51 UTC, hidec-7 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    }
> 1点追加で修正依頼です！
> 基本的に型は指定を依頼したいですー
> (Anyはほぼ型の指定なしとほぼ同義です！)
> 
> 型指定して欲しい理由として2つあるので、共有です。
> 
> 1. Swiftは型指定をしっかりしている静的言語
> 2. 型を指定しないとどんなメソッドか想像しづらい
>    →例えばbackToGameManagement(_ sender: Any)だと型がわからず、
>    storyboardを見て、型がBarButtonItemだとわかりボタンをタップした時の処理だと理解できました！
>    ただ、storyboardを見ると言う手間が少々面倒くさいです。
>    そういった手順が多くなると、コードの可読性がどんどん下がってしまいます。
> 
> それを解決するために型を指定する方法です！
> 
> backToGameManagement(_ sender: UIButton)
> ↑例えばこれだと一瞬でボタンに押した時のメソッドだと予想できるのでコードを読むハードルがめっちゃ下がります！
> また、型指定されているのでSwiftっぽいです！

なるほどです！
全くそんなこと考えたことなかったです！
めちゃくちゃ勉強になります！

修正します！

2020-11-24 07:55 UTC, hidec-7 commented
修正しました！

2020-11-24 14:27 UTC, fuchi0741 requested changes
@hidec-7 コメントしましたー！
確認お願いしますー！

2020-11-24 14:27 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    @IBAction func backToGameManagement(_ sender: UIButton) {
このUIButtonって直打ちしました？
型はUIButtonではなく別の型なので気になりました、、！

2020-11-24 14:28 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    @IBAction func backToGameManagement(_ sender: UIButton) {
直打ちではない方法があるので、ググってみてください！

2020-11-24 14:34 UTC, hidec-7 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    @IBAction func backToGameManagement(_ sender: UIButton) {
> このUIButtonって直打ちしました？
> 
> 型はUIButtonではなく別の型なので気になりました、、！

直打ちです！

2020-11-24 14:34 UTC, hidec-7 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    @IBAction func backToGameManagement(_ sender: UIButton) {
> 直打ちではない方法があるので、ググってみてください！

なるほどです！
了解しました！

2020-11-24 14:36 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    @IBAction func backToGameManagement(_ sender: UIButton) {
@hidec-7 
修正が終わった後に修正した旨のコメントをいただけるとスムーズにレビューできると思いました！
(通知 = レビューに極力したいです、、！)

もちろん質問等や説明がわからなかった等については別途聞いてください!

2020-11-24 14:37 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    @IBAction func backToGameManagement(_ sender: UIButton) {
@hidec-7 
リアクションのみであればスタンプのみで大丈夫ですよ！

2020-11-24 14:43 UTC, hidec-7 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    @IBAction func backToGameManagement(_ sender: UIButton) {
> @hidec-7
> 修正が終わった後に修正した旨のコメントをいただけるとスムーズにレビューできると思いました！
> (通知 = レビューに極力したいです、、！)
> 
> もちろん質問等や説明がわからなかった等については別途聞いてください!

わかりました！

2020-11-24 14:49 UTC, fuchi0741 approved these changes
@hidec-7 LGTM👍

2020-11-24 14:50 UTC, hidec-7 commented
@fuchi0741 
修正しました！

2020-11-24 14:50 UTC, merged