試合登録画面　前半・後半・まとめ: StackView,Label,TextView 実装
hidec-7/MySoccerNoteApp pull request #21
Opened 2020-11-24 18:09 UTC by hidec-7

**clone コマンド**
git clone -b feature/add-UI-Impression-Item https://github.com/hidec-7/SoccerNoteDev.git

**Trello**
試合登録画面 前後半・まとめ 実装

**概要**
試合登録画面の前半・後半・まとめのLabelとTextViewを実装。
LabelとTextViewをオートレイアウトを考えてStackViewを実装しました。

**レビューで見て欲しいポイント**
オートレイアウトに問題はないか。

**実機build/期待通りの挙動をするか**
OK

※UI変更した場合のみ記述

**11 Pro や SE など大きさが異なる端末のレイアウトが崩れていないか？**
OK

**レビュー依頼**
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741

**補足**
基本的に実装はできたのですが、レイアウトの所で悩んでいます。
SEでのレイアウトが少し無理やり感が出ているような気がして、、、
前に少し話をしたと思うのですが、Cellを使ってスクロールできるようにした方が今回のような時にいいと言う話で、やっぱりCellを使うべきなのでしょうか。
しかし、そうなるとかなり実装にまた時間がかかると思ったりもします。
ふちさんの意見を聞かせて頂けたらと思います。
![image](https://user-images.githubusercontent.com/66632738/100134461-96e8a580-2ecb-11eb-831c-3b73f4657361.png)

2020-11-24 19:38 UTC, fuchi0741 requested changes
@hidec-7 コメントしましたー！

2020-11-24 19:38 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +
同じsetup関連だとわかるので、L33は余計なスペースかと思いました。

2020-11-24 19:39 UTC, fuchi0741 commented
レイアウトに関してですが、めっちゃキレイだと思いました！
無理やり感は特に感じなかったですねmm

なのでCellでやる必要は特にないのでは?と思ってます！

2020-11-24 19:41 UTC, fuchi0741 commented
ちょっと応用になりますが、
アクセス修飾子を追加で実装できると、より可読性の高いコードが実現できるのではと思いました！

もし対応するってなったら別チケットでいいかと思いますー

2020-11-24 19:42 UTC, fuchi0741 commented
あとキーボードが下がらないので、対応お願いしますー！
別チケットでもいいかなって思います

2020-11-25 05:14 UTC, hidec-7 commented
> レイアウトに関してですが、めっちゃキレイだと思いました！
> 無理やり感は特に感じなかったですねmm
> 
> なのでCellでやる必要は特にないのでは?と思ってます！

ほんとですか！
よかったです！
このままでいきたいと思います！

2020-11-25 05:17 UTC, hidec-7 commented
> ちょっと応用になりますが、
> アクセス修飾子を追加で実装できると、より可読性の高いコードが実現できるのではと思いました！
> 
> もし対応するってなったら別チケットでいいかと思いますー

アクセス修飾子って初めて聞いて調べて、まだ理解が浅いのですがprivateとかpublicを付けてクラス内部のみで使うのかグローバルに使うのかをパッと見でわかるようにすると言った感じであってますかね？

2020-11-25 05:18 UTC, hidec-7 commented
> あとキーボードが下がらないので、対応お願いしますー！
> 別チケットでもいいかなって思います

忘れてました！
ここで修正します！

2020-11-25 11:22 UTC, fuchi0741 commented
> > ちょっと応用になりますが、
> > アクセス修飾子を追加で実装できると、より可読性の高いコードが実現できるのではと思いました！
> > もし対応するってなったら別チケットでいいかと思いますー
> 
> アクセス修飾子って初めて聞いて調べて、まだ理解が浅いのですがprivateとかpublicを付けてクラス内部のみで使うのかグローバルに使うのかをパッと見でわかるようにすると言った感じであってますかね？

デフォルトがpublicなのでpublicは書かなくても大丈夫ですね！
書くとしたらprivateですね！

2020-11-25 14:58 UTC, hidec-7 commented
> > > ちょっと応用になりますが、
> 
> > > アクセス修飾子を追加で実装できると、より可読性の高いコードが実現できるのではと思いました！
> 
> > > もし対応するってなったら別チケットでいいかと思いますー
> 
> > 
> 
> > アクセス修飾子って初めて聞いて調べて、まだ理解が浅いのですがprivateとかpublicを付けてクラス内部のみで使うのかグローバルに使うのかをパッと見でわかるようにすると言った感じであってますかね？
> 
> 
> 
> デフォルトがpublicなのでpublicは書かなくても大丈夫ですね！
> 
> 書くとしたらprivateですね！

なるほどです！
わかりました！

2020-11-26 05:37 UTC, fuchi0741 commented
> > > > ちょっと応用になりますが、
> > 
> > 
> > > > アクセス修飾子を追加で実装できると、より可読性の高いコードが実現できるのではと思いました！
> > 
> > 
> > > > もし対応するってなったら別チケットでいいかと思いますー
> > 
> > 
> > > 
> > 
> > 
> > > アクセス修飾子って初めて聞いて調べて、まだ理解が浅いのですがprivateとかpublicを付けてクラス内部のみで使うのかグローバルに使うのかをパッと見でわかるようにすると言った感じであってますかね？
> > 
> > 
> > デフォルトがpublicなのでpublicは書かなくても大丈夫ですね！
> > 書くとしたらprivateですね！
> 
> なるほどです！
> わかりました！

すいませんリアクションレベルはスタンプで大丈夫ですよ！👍

2020-11-26 07:59 UTC, hidec-7 commented
Approveお願いします！

2020-11-26 08:02 UTC, fuchi0741 approved these changes
@hidec-7 LGTM👍
余計なスペース関連の指摘はしましたが修正はお任せしますー！

2020-11-26 08:06 UTC, hidec-7 commented
あ！ほんとですね！笑
すいません！
修正しときます！

2020-11-26 08:06 UTC, hidec-7 commented
> @hidec-7 LGTM👍
> 
> 余計なスペース関連の指摘はしましたが修正はお任せしますー！

あ！ほんとですね！笑
すいません！
修正しときます！

2020-11-26 08:24 UTC, merged