試合登録画面 登録ボタン実装
hidec-7/MySoccerNoteApp pull request #22
Opened 2020-11-27 04:16 UTC by hidec-7

**clone コマンド**
git clone -b feature/add-UI-Register-Button https://github.com/hidec-7/SoccerNoteDev.git

**Trello**
試合登録画面 登録ボタン実装

**概要**
登録ボタンを実装。
ボタンタップで試合管理画面に画面遷移。

**レビューで見て欲しいポイント**
オートレイアウトの付け方。

**実機build/期待通りの挙動をするか**
OK

※UI変更した場合のみ記述

**11 Pro や SE など大きさが異なる端末のレイアウトが崩れていないか？**
OK

**レビュー依頼**
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741

2020-11-27 06:30 UTC, fuchi0741 requested changes
@hidec-7 コメントしましたー！

2020-11-27 06:30 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    }
名称に統一感が欲しいですmm

backToが後なのか先なのか


もっと言えばbackToがそもそもいらないかもですね。
dismissを見れば、backしているのが伝わりますし、このメソッドで重要なことはバックすることではなく登録ができることなので！

2020-11-27 06:30 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    }
あと一つ伝え忘れていました！

action接続の時の命名は
didTapXxx を推奨します！
(didTapxxx とすることでタップした後に呼ばれるメソッドだと認知できるので！
あんま使わないですが、didTap以外のタイミングもあるので、、、)

L20と合わせて修正した方がいいかもです！

2020-11-27 06:30 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    }
backToGameManagement
も
didTapBackButton とかでいいかもですねmm

2020-11-27 06:30 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    }
何か気になることがあればコメントくださいー！

2020-11-27 06:30 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +        setupRegisterButton()
ちょっと応用ですが、setup関係のメソッドが増えてきたので、それらをまとめるメソッドを作成してもいいかもですね。
修正はまとめます！

見やすくなると思っただけですー！
ライフサイクル内のコードは少なければ少ないほどOKです！

```Swift
func setupFirst() {
    setupKeyboard()
    setupTextView()	        
    setupRegisterButton()
}
```

2020-11-27 06:32 UTC, fuchi0741 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    }
didTapRegisterButton とかでいいかもですね

2020-11-27 06:35 UTC, fuchi0741 commented
レイアウトはめっちゃいい感じだと思いますよ！！！
あとは他の小さい端末で見ても問題なさそうであればOKです！

2020-11-27 06:40 UTC, fuchi0741 commented
一個質問ですが、データの永続化にはFirebaseを使用する認識であっていますか？

2020-11-27 16:48 UTC, hidec-7 commented on SoccerNoteApp/GameRegisterViewController.swift
> +    }
命名修正します！

2020-11-27 16:51 UTC, hidec-7 commented
> レイアウトはめっちゃいい感じだと思いますよ！！！
> あとは他の小さい端末で見ても問題なさそうであればOKです！
> 
> たぶんTextViewが可変になっているので、いい感じにレイアウトできている気がします

ありがとうございます！
よかったです！
レイアウト少し慣れてきた気がします笑

2020-11-27 16:51 UTC, hidec-7 commented
> 一個質問ですが、データの永続化にはFirebaseを使用する認識であっていますか？

はい！！

2020-11-27 17:05 UTC, hidec-7 commented
@fuchi0741 
修正しました！

2020-11-28 00:27 UTC, fuchi0741 approved these changes
@hidec-7 LGTM👍

2020-11-28 02:06 UTC, merged