試合編集画面　実装
hidec-7/MySoccerNoteApp pull request #28
Opened 2020-12-04 17:32 UTC by hidec-7

**clone コマンド**
git clone -b feature/add-UI-gameEdit https://github.com/hidec-7/SoccerNoteDev.git

**Trello**
試合編集画面　実装

**概要**
試合編集画面を実装しました。
UIは全く試合登録画面と一緒です。

**レビューで見て欲しいポイント**
setupのメソッドの命名が試合登録画面と全く同じものがあるのですが、それは問題ないのでしょうか。
少しお話した部分なのですが、この場合extensionを使った方が良いのかレビュー頂きたいです。

**実機build/期待通りの挙動をするか**
OK

※UI変更した場合のみ記述

**11 Pro や SE など大きさが異なる端末のレイアウトが崩れていないか？**
OK

**レビュー依頼**
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741

2020-12-05 13:11 UTC, fuchi0741 requested changes
@hidec-7 コメントしましたー！
確認お願いしますー！

2020-12-05 13:11 UTC, fuchi0741 commented on SoccerNoteApp/GameEditViewController.swift
> +class GameEditViewController: UIViewController,UITextFieldDelegate,UINavigationBarDelegate {
,のあとにスペースがないのが気になりますmm

2020-12-05 13:11 UTC, fuchi0741 commented on SoccerNoteApp/GameEditViewController.swift
> +    @IBOutlet weak var registerEditButton: UIButton!
ちょっと応用ですが、実はここにもアクセス修飾子がつけられますmm

2020-12-05 13:11 UTC, fuchi0741 commented on SoccerNoteApp/GameEditViewController.swift
> +    @IBOutlet weak var registerEditButton: UIButton!
registerEditって名称が登録なのか編集なのかどっちかわからないですmm
editButtonでいいかなと思いますー！

2020-12-05 13:11 UTC, fuchi0741 commented on SoccerNoteApp/GameEditViewController.swift
> +    @IBAction func didTapRegisterEditButton(_ sender: UIButton) {
ここもメソッドが登録か編集かわからないので修正お願いしますー！

2020-12-05 13:11 UTC, fuchi0741 commented on SoccerNoteApp/GameEditViewController.swift
> +        self.dismiss(animated: true, completion: nil)
selfは書かなくてもいいので削除推奨ですー！

selfは書くことが必須の場合のみ記述というルールの現場は多いです！

2020-12-05 13:11 UTC, fuchi0741 commented on SoccerNoteApp/GameEditViewController.swift
> +        self.dismiss(animated: true, completion: nil)
ここもself削除推奨ですー！

2020-12-05 13:11 UTC, fuchi0741 commented on SoccerNoteApp/GameEditViewController.swift
> +        self.opponentScoreEditTextField.keyboardType = UIKeyboardType.numberPad
self不要ですー！”

2020-12-05 13:11 UTC, fuchi0741 commented on SoccerNoteApp/GameEditViewController.swift
> +        registerEditButton.layer.cornerRadius = 15.0
命名修正お願いしますー！

2020-12-05 13:11 UTC, fuchi0741 commented on SoccerNoteApp/GameEditViewController.swift
> +
余計なスペースの削除をお願いしますー！

2020-12-05 13:11 UTC, fuchi0741 commented on SoccerNoteApp/GameManagementViewController.swift
> +
余計なスペースですー！

2020-12-05 13:11 UTC, fuchi0741 commented on SoccerNoteApp/Base.lproj/Main.storyboard
> +                                <state key="normal" title="登録">
編集画面なので登録ボタンと言うのは不自然だと思いましたmm

2020-12-07 09:50 UTC, hidec-7 commented on SoccerNoteApp/GameEditViewController.swift
> +    @IBOutlet weak var registerEditButton: UIButton!
> ちょっと応用ですが、実はここにもアクセス修飾子がつけられますmm

つけた方がいいですよね？

2020-12-07 15:57 UTC, fuchi0741 commented on SoccerNoteApp/GameEditViewController.swift
> +    @IBOutlet weak var registerEditButton: UIButton!
@hidec-7 チャレンジしてみてもいいかもです！
保守性はめちゃ高くなります！

任せます！

2020-12-08 02:08 UTC, hidec-7 commented on SoccerNoteApp/Base.lproj/Main.storyboard
> +                                <state key="normal" title="登録">
> 編集画面なので登録ボタンと言うのは不自然だと思いましたmm

ナビゲーションバータイトルを編集に変えてボタンをそのまま登録にして
編集を登録と言った感じにしてみたのですが、どうでしょうか？

2020-12-08 02:08 UTC, fuchi0741 commented
@hidec-7 修正終わっていたらメンションをつけて教えてくださいー！

2020-12-08 02:09 UTC, hidec-7 commented
> @hidec-7 修正終わっていたらメンションをつけて教えてくださいー！

すいません！

2020-12-08 02:13 UTC, hidec-7 commented
@fuchi0741 修正しました！

2020-12-08 02:32 UTC, fuchi0741 commented on SoccerNoteApp/Base.lproj/Main.storyboard
> +                                <state key="normal" title="登録">
@hidec-7 いいと思います！

2020-12-08 02:32 UTC, fuchi0741 commented on SoccerNoteApp/GameEditViewController.swift
> +    @IBOutlet weak var registerEditButton: UIButton!
@hidec-7 
ここは一旦スルーですか？

2020-12-08 02:32 UTC, fuchi0741 approved these changes
@hidec-7 LGTM👍

2020-12-08 02:35 UTC, hidec-7 commented on SoccerNoteApp/GameEditViewController.swift
> +    @IBOutlet weak var registerEditButton: UIButton!
> @hidec-7
> ここは一旦スルーですか？

あ、すいませんあとで考えて返信しようと思って忘れていました！
ここのアクセス修飾子って他と同じでprivateを付けるんですかね？

2020-12-08 02:48 UTC, hidec-7 commented
@fuchi0741 
アクセス修飾子追記してみたのですがこんな感じで間違いないですかね？

2020-12-08 04:04 UTC, fuchi0741 commented
@hidec-7 はい！いい感じです！
IBActionは必要ないかなと思いましたが、IBOutletのみでいいかなと思っていましたがOKです！

今後ActionにつけていただいたPrivateを外すことになるかと思いますmm

2020-12-08 04:23 UTC, merged