Feature/add login firebase
hidec-7/MySoccerNoteApp pull request #37
Opened 2020-12-15 16:55 UTC by hidec-7

**clone コマンド**
git clone -b feature/add-login-Firebase https://github.com/hidec-7/SoccerNoteDev.git

**Trello**
匿名ログイン

**概要**
Firebaseを用いて匿名ログインを実装。

**レビューで見て欲しいポイント**
匿名ログインに関しては問題なく実装できたと思うのですが、
やっぱりPodsの余計な差分が無くなりませんでした。
これの原因をアドバイス頂けないでしょうか。

**実機build/期待通りの挙動をするか**
OK

**レビュー依頼**
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741

2020-12-16 14:12 UTC, fuchi0741 commented
> やっぱりPodsの余計な差分が無くなりませんでした。
> これの原因をアドバイス頂けないでしょうか。

基本的にアドバイスを求めるときは質問フォーマットにそってやってください！
(何をやったかの背景がわからないとアドバイスしたくても意外とできないんですよmm)

そもそもこのPRでpodsの差分をなすくチャレンジはしたのですか？

2020-12-16 14:14 UTC, fuchi0741 commented on SoccerNoteApp/Controller/AppDelegate.swift
> +        }
ここはmodel化できる部分だと思うのでModelのチャレンジをしてみましょう！
このPRでやるか、別PRでやるかは任せますー！

2020-12-16 15:56 UTC, hidec-7 commented
> > やっぱりPodsの余計な差分が無くなりませんでした。
> > これの原因をアドバイス頂けないでしょうか。
> 
> 基本的にアドバイスを求めるときは質問フォーマットにそってやってください！
> (何をやったかの背景がわからないとアドバイスしたくても意外とできないんですよねmm)
> 
> あとは質問する場合は、自分で考えた感を出せるといいですmm
> (ほんとに考えてもわからない場合はあるのですが、そのときはそう言った方がいいですmm)

すいません！

今回、このPRかラインかどちらで質問フォーマット送る方がいいですかね？

2020-12-16 15:57 UTC, hidec-7 commented on SoccerNoteApp/Controller/AppDelegate.swift
> +        }
> ここはmodel化できる部分だと思うのでModelのチャレンジをしてみましょう！
> このPRでやるか、別PRでやるかは任せますー！

やってみます！
このPRでやります！

2020-12-17 05:03 UTC, fuchi0741 commented
> 今回、このPRかラインかどちらで質問フォーマット送る方がいいですかね？

PRでお願いしますー！

2020-12-17 06:28 UTC, hidec-7 commented
> > 今回、このPRかラインかどちらで質問フォーマット送る方がいいですかね？
> 
> 
> 
> PRでお願いしますー！
> 
> 
> 
> 

了解です！

2020-12-17 07:53 UTC, hidec-7 commented
**1. 質問の概要(必須項目)**
Pods関連の差分を無くすため、2度の修正をし解決しようとしたのですができませんでした。
調べてやってみた所、他に原因が自分ではわかりませんでした。
アドバイス頂けませんでしょうか。

**2. 前提となる情報(必須項目)**
 - その他参考にした記事1: https://qiita.com/kasajei/items/8c9ba3030c3eae736e89
 - その他参考にした記事2: https://teratail.com/questions/176040

**3. 期待する挙動(必須項目)**
新たにPodインストールをした時に、余計な差分が大量に出てしまいます。
この差分をPodsを.gitignoreで管理外にして無くしたいです。

**4. 発生したエラーや意図しない挙動の説明(必須項目)**
.gitignoreでPodsを管理外にしたつもりなのですが、PRを出した際にやはり差分が出てきてしまいます。

**5. デバッグ内容と自身の考察(必須項目)**
まずPodsの余計な差分を無くすために、.gitignoreで管理外にすることが必須だと思いました。
なので以下の2つのやり方でアプローチしました。
- .gitignoreにPods/*を追記して管理外にしてみました。これは.gitignoreで管理すべきファイルでググると出てきたのと多くの人がPods/*を追記してるようだと思ったので、試しました。しかし、これでは管理外にできませんでした。
- 次に記述が違うのかと考え、違った記述方法で_プロジェクト名/Pods/_で試したのですが、できませんでした。

**6. 求める回答(必須項目)**
- .gitignoreの記述内容に間違いはないか。
- 問題点が自分の考える所と違った所にあるのか。
アドバイス頂きたいです。

**8. その他参考となりそうな情報(任意項目)**
![image](https://user-images.githubusercontent.com/66632738/102458982-59b9a280-4088-11eb-89f3-83f4f612300f.png)

@fuchi0741

2020-12-17 17:11 UTC, hidec-7 commented
ログイン実装の所をModel化やってみました！
一応、ユーザー情報もFirebaseに保存されたのでできたかと思います！

Model化の実装方法に問題はないか。
変数やファイルの命名など、問題ないか。

この辺のレビューを頂けたらと思います。

@fuchi0741

2020-12-18 16:38 UTC, hidec-7 commented
質問、修正に関してコメントしましたー！
@fuchi0741

2020-12-20 12:27 UTC, fuchi0741 commented
質問していただいた内容なのですが、ヒデトさんに共有していただいた


https://teratail.com/questions/176040

でやれば解決できそうな感じがしたのですが、試してみましたか？
キャッシュだとか、！

スクショありがとうございます！！！！

あとこのPRでは一旦匿名ログインに注力するとして、Podsを管理外に設定するのは一旦別PRで対応しましょう！

2020-12-20 12:38 UTC, fuchi0741 requested changes
@hidec-7 割と多めにレビューしました！
後、余計なスペースもいくつか見つかったので修正お願いします！

不明点があれば質問くださいー！

2020-12-20 12:38 UTC, fuchi0741 commented on SoccerNoteApp/Controller/AppDelegate.swift
> +    var loginModel = LoginModel()
**let**でよさそうです！

loginModelの値が変化するという訳ではないので！

ver か let 両方使用できる場合はletを使用しましょう！

2020-12-20 12:38 UTC, fuchi0741 commented on SoccerNoteApp/Controller/AppDelegate.swift
> +        loginModel.loginFunction()
`loginModel.loginFunction()`

ここが冗長に感じます、、！
ログインログインと複数使用しているので、そう感じました！

2020-12-20 12:38 UTC, fuchi0741 commented on SoccerNoteApp/Model/LoginModel.swift
> +import UIKit
UIKitをimportする必要はないと思います！

2020-12-20 12:38 UTC, fuchi0741 commented on SoccerNoteApp/Model/LoginModel.swift
> +    func loginFunction() {
命名にFunctionといれる必要はないと思いました！
理由は2つです

1) func xxx の時点でメソッドだと理解できる
2) 呼び出すとき(今回だと`loginModel.loginFunction()`)は命名の最後に()があるので、メソッドを呼んでいると予想できる

メソッド = function ととりあえず思っていただいて大丈夫です！

2020-12-20 12:38 UTC, fuchi0741 commented on SoccerNoteApp/Model/LoginModel.swift
> +class LoginModel {
LoginModelのネーミングはいいと思いました！

2020-12-20 12:38 UTC, fuchi0741 commented on SoccerNoteApp/Model/LoginModel.swift
> +                print("Auth Error :\(error!.localizedDescription)")
`error!.localizedDescription`

基本的に「!」は使用してはいけないくらいの意識があるといいと思います！
意図しないバグが発生する温床になるので！

オプショナルバインディングという手法を使って、!を使用しないように修正をしてみてください！

2020-12-20 12:38 UTC, fuchi0741 commented on SoccerNoteApp/Model/LoginModel.swift
> +            let uid = user.uid
ここの定数は使用しないので、ワイルドカード化してもいいと思いました！

_ = user.isAnonymous 

こんなイメージですね！

2020-12-20 12:39 UTC, fuchi0741 commented on SoccerNoteApp/Controller/AppDelegate.swift
> +        loginModel.loginFunction()
loginModel.anonymous() 
とかでも伝わりますね！

2020-12-20 12:40 UTC, fuchi0741 commented
model化に関してはいい感じだと思いました！

2020-12-20 12:53 UTC, hidec-7 commented
> model化に関してはいい感じだと思いました！

ありがとうございます！

2020-12-20 14:22 UTC, hidec-7 commented on SoccerNoteApp/Model/LoginModel.swift
> +                print("Auth Error :\(error!.localizedDescription)")
> `error!.localizedDescription`
> 
> 基本的に「!」は使用してはいけないくらいの意識があるといいと思います！
> 意図しないバグが発生する温床になるので！
> 
> オプショナルバインディングという手法を使って、!を使用しないように修正をしてみてください！

すいません、自分で実装しといてあれなんですけど、そもそも16,17行って必要ですか？

2020-12-21 04:11 UTC, fuchi0741 commented on SoccerNoteApp/Model/LoginModel.swift
> +                print("Auth Error :\(error!.localizedDescription)")
L16,17は匿名ログインに失敗した場合に、なんで失敗してエラーが出たのかを知るために必要ですね！
(エラーハンドリングっていいます！)

個人開発だと必要性あまり感じないかも知れないですが、仕事だと例えばユーザーがログインできないって問い合わせがきた時にエラーハンドリングのログを参考にして出来ない原因を伝えたりする業務があります。

もし、L16,17がなかったらトンチンカンな回答をユーザーに繋がってクレームとか評価低下に繋がりますmm

2020-12-21 04:11 UTC, fuchi0741 commented on SoccerNoteApp/Model/LoginModel.swift
> +                print("Auth Error :\(error!.localizedDescription)")
@hidec-7

2020-12-22 04:29 UTC, hidec-7 commented on SoccerNoteApp/Model/LoginModel.swift
> +                print("Auth Error :\(error!.localizedDescription)")
> L16,17は匿名ログインに失敗した場合に、なんで失敗してエラーが出たのかを知るために必要ですね！
> (エラーハンドリングっていいます！)
> 
> 個人開発だと必要性あまり感じないかも知れないですが、仕事だと例えばユーザーがログインできないって問い合わせがきた時にエラーハンドリングのログを参考にして出来ない原因を伝えたりする業務があります。
> 
> もし、L16,17がなかったらトンチンカンな回答をユーザーに繋がってクレームとか評価低下に繋がりますmm

なるほどです！
必要性すごく理解できました！
わかりやすい説明ありがとうございます！

2020-12-22 05:36 UTC, hidec-7 commented
指摘部分修正しました！
@fuchi0741

2020-12-22 05:39 UTC, hidec-7 commented on SoccerNoteApp/Model/LoginModel.swift
> +                print(AuthError)
オプショナルバインディングをやってみたのですが、これ間違ってますよね？ｗ
なんとなくの感覚でやってしまったのですが。

2020-12-22 05:44 UTC, hidec-7 commented
オプショナルバインディングやってみたのですが、なんかおかしいですよね？ｗ
なんとなくこんな感じかなと思い感覚でやってみたのですが

2020-12-23 12:32 UTC, hidec-7 commented
@

> 指摘部分修正しました！

2020-12-23 12:32 UTC, hidec-7 commented
指摘部分修正しました！

2020-12-23 12:33 UTC, hidec-7 commented
@fuchi0741

2020-12-23 13:34 UTC, fuchi0741 reviewed
@hidec-7 コメントしました〜！

2020-12-23 13:34 UTC, fuchi0741 commented on SoccerNoteApp/Model/LoginModel.swift
> +                print(AuthError)
`localizedDescription`でエラーの詳細をハンドリングできるように修正をお願いしますー！

あと命名ですが、`AuthError`が若干冗長に感じました！
理由は、L17,18は匿名ログイン実行内のみの処理を記述していてスコープが狭いからです！

つまり、errorだけでも匿名ログイン周りのエラーなのが伝わるんですよね！
Authといわなくても！

2020-12-23 16:27 UTC, hidec-7 commented on SoccerNoteApp/Model/LoginModel.swift
> +                print(AuthError)
> `localizedDescription`でエラーの詳細をハンドリングできるように修正をお願いしますー！
> 
> 
> 
> あと命名ですが、`AuthError`が若干冗長に感じました！
> 
> 理由は、L17,18は匿名ログイン実行内のみの処理を記述していてスコープが狭いからです！
> 
> 
> 
> つまり、errorだけでも匿名ログイン周りのエラーなのが伝わるんですよね！
> 
> Authといわなくても！

命名なんですけど、errorにすると　error = error になるんですけどそれって問題ないんですかね？

2020-12-23 17:10 UTC, fuchi0741 commented on SoccerNoteApp/Model/LoginModel.swift
> +                print(AuthError)
@hidec-7 別物なので問題ないですー！
オプショナルバインディングについてググってみてくださいー！

https://qiita.com/chino_tweet/items/4b59d1751e62248a2ece

2020-12-29 16:44 UTC, hidec-7 commented
修正しました！
こんな感じですかね？
@fuchi0741

2020-12-29 16:56 UTC, fuchi0741 reviewed
@hidec-7 コメントしましたー！

2020-12-29 16:56 UTC, fuchi0741 commented on SoccerNoteApp/Model/LoginModel.swift
> +                print("")
elseの中身がprint("")のみであれば、記述がないことと等しいので削除しましょう！

あと今回は大丈夫ですが、guard-letでもよかったかもですね！

2020-12-29 17:00 UTC, hidec-7 commented on SoccerNoteApp/Model/LoginModel.swift
> +                print("")
print()でいいんですかね？
どっちがいいか迷いました笑
とりあえずif-letでいいかなと思ってやりました！

2020-12-29 17:01 UTC, fuchi0741 commented on SoccerNoteApp/Model/LoginModel.swift
> +                print("")
@hidec-7 elseがそもそも必要ないですね！
elseを書かなきゃいけないわけでもないので記述する必要がなければ書かなくてOKです！

2020-12-29 17:03 UTC, hidec-7 commented on SoccerNoteApp/Model/LoginModel.swift
> +                print("")
なるほどです！
修正します！
@fuchi0741

2020-12-29 17:05 UTC, hidec-7 commented
修正しました！
@fuchi0741

2020-12-29 17:14 UTC, fuchi0741 approved these changes
@hidec-7 LGTM👍

2020-12-29 17:31 UTC, merged