Firebase CRUD(Create) 実装
hidec-7/MySoccerNoteApp pull request #43
Opened 2021-01-05 05:35 UTC by hidec-7

**clone コマンド**
git clone -b feature/create-database https://github.com/hidec-7/SoccerNoteDev.git

**Trello**
CRUD(C:作成)

**概要**
Firebase: Realtime Databaseでデータベースを作成し、試合登録のデータを送信（保存）を実装。

**レビューで見て欲しいポイント**
コードの書き方。実装方法に問題はないか。
(Modelは一切考えず、とにかくデータの送信（保存）ができるように実装しました）

**実機build/期待通りの挙動をするか**
OK

**レビュー依頼**
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741

2021-01-06 07:54 UTC, fuchi0741 commented
実際に動作確認をしたいので、
Firebaseのアカウントで使用したアドレスとパスワードを教えてくださいー！

2021-01-06 08:00 UTC, fuchi0741 reviewed
@hidec-7 簡単にレビューしました！
詳細は今日の夜にやります！

2021-01-06 08:00 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +class GameRegisterViewController: UIViewController,UITextFieldDelegate,UINavigationBarDelegate,UITextViewDelegate {
, の後ろは半角スペースを入れるのが一般的なので修正お願いしますー！
```Swift
class GameRegisterViewController: UIViewController,　UITextFieldDelegate,　UINavigationBarDelegate,　UITextViewDelegate {
```

2021-01-06 08:00 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +    @IBOutlet weak var registerDate: UIDatePicker!
DataPickerというのを命名に入れたいです！
また登録した日時ではなく、試合の日時を登録するのが要件だと思っているので、
`gameDatePicker`という命名だとわかりやすいと思いました。

2021-01-06 08:00 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +    }
この辺の指摘はもうちょっと時間とってレビューします！
今日の夜には実施予定です！すいません！

2021-01-06 08:00 UTC, fuchi0741 commented
@hidec-7 質問ですが、Medel化は別チケットで対応予定ですか？

2021-01-06 08:17 UTC, fuchi0741 commented
@hidec-7 ファイルの差分が減っていい感じですね笑

2021-01-06 08:26 UTC, hidec-7 commented
> 実際に動作確認をしたいので、
> 
> Firebaseのアカウントで使用したアドレスとパスワードを教えてくださいー！

hiedematoaho0730127@gmail.com
Hc0727246

違ったら連絡ください！

2021-01-06 08:27 UTC, hidec-7 commented
> @hidec-7 質問ですが、Medel化は別チケットで対応予定ですか？

このブランチでいいかなって思ってます！

2021-01-06 08:27 UTC, hidec-7 commented
> @hidec-7 ファイルの差分が減っていい感じですね笑

ほんとですね笑
よかったです笑

2021-01-06 08:28 UTC, fuchi0741 commented
> > @hidec-7 質問ですが、Medel化は別チケットで対応予定ですか？
> 
> このブランチでいいかなって思ってます！

その場合はWIPをつけてくださいmm

2021-01-06 08:45 UTC, hidec-7 commented
> > > @hidec-7 質問ですが、Medel化は別チケットで対応予定ですか？
> 
> > 
> 
> > このブランチでいいかなって思ってます！
> 
> 
> 
> その場合はWIPをつけてくださいmm
> 
> まだ開発が完了していないということなので！

なるほどです！
了解しました！

2021-01-06 14:06 UTC, hidec-7 commented
@fuchi0741 指摘部分修正しました！

2021-01-07 07:37 UTC, fuchi0741 commented
@hidec-7 一応共有すると、、、
WIP = 今開発中なのでレビューはまだ大丈夫です！
という意味になるため、WIP外れたらレビューしますね！！！

2021-01-07 09:09 UTC, hidec-7 commented
> @hidec-7 一応共有すると、、、
> 
> WIP = 今開発中なのでレビューはまだ大丈夫です！
> 
> という意味になるため、WIP外れたらレビューしますね！！！

あ。すいません！！ほんとですね！
今の場合、修正完了したらWIP外して、修正中はWIPつける
で間違いないですかね？

2021-01-07 13:58 UTC, fuchi0741 commented
> 修正完了したらWIP外して、修正中はWIPつける

レビュー依頼投げるタイミングでWIPを外すイメージです！
ただ、レビュー指摘を受けて修正をする場合はWIPはつけなくて大丈夫です！

あとWIP外したらメンションつけてくださいね！

2021-01-07 19:57 UTC, hidec-7 commented
> > 修正完了したらWIP外して、修正中はWIPつける
> 
> 
> 
> レビュー依頼投げるタイミングでWIPを外すイメージです！
> 
> ただ、レビュー指摘を受けて修正をする場合はWIPはつけなくて大丈夫です！
> 
> 
> 
> あとWIP外したらメンションつけてくださいね！

なるほどです！
理解不足ですいません！
ありがとうございます！

2021-01-08 05:24 UTC, hidec-7 commented
@fuchi0741

2021-01-08 09:08 UTC, fuchi0741 commented
https://support.google.com/firebase/answer/7000272?hl=ja
ひでとさんすいません。アカウントの権限が追加できるようなので追加していただいてもよろしいですか？？
以下のアドレスを追加お願いします！
fuchi.kazuma@gmail.com

2021-01-08 09:11 UTC, fuchi0741 commented
WIPが外れていますが、Model化は別ブランチで実施ということで大丈夫ですか？

2021-01-08 09:43 UTC, fuchi0741 requested changes
@hidec-7 少々多いですが、コメントしました！
ご確認お願いします！

2021-01-08 09:43 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +            "matome": matome as Any,
as Any は極力避けたいですね！
型指定をすれば問題なのため、L50-53のインスタンス化の箇所を型指定してあげると解消されます！
ex) `let zenhan: String = firstHalfTextView.text`

2021-01-08 09:43 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +        ] as [String : Any]
`as [String : Any]`ここの型指定がしなくてもいいのではと思いました！(型推論の時点で[String: Any型なので])

2021-01-08 09:43 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +        ref.child((Auth.auth().currentUser?.uid)!).childByAutoId().setValue(registerData)
`((Auth.auth().currentUser?.uid)!)`
以下の2点気になりました。

- ()が二重のため見ずらい
- 強制アンラップ(!のこと)は基本的に許容できない

これらを解決するためにguard分を使用するといいと思います！
`guard let uid = Auth.auth().currentUser?.uid  else { return }` 
↑はUIDがなかったら処理を中断するものなのでラップをする必要がなくなります。

` ref.child(uid).childByAutoId().setValue(registerData)`
と書くことができスッキリした印象にできるかなと思います。
参考にどうぞ！

2021-01-08 09:43 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +        ref.child((Auth.auth().currentUser?.uid)!).childByAutoId().setValue(registerData)
また、`registerData`という命名も気になりました。
というのも今は試合結果しか登録していないためregisterData = 試合結果 とわかるのですが
今後健康データや練習内容の記録機能を拡大した場合、registerData = 試合結果 となるのは混乱のものになり得るからです！

そのため`gameData`という命名がいいのではと思っています。

2021-01-08 09:43 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +    @IBOutlet weak private var registerDatePicker: UIDatePicker!
このDatePickerの日時の使用って送信した日時ではなくて試合した日ですよね？
`registerDatePicker`だと送信した日時のように感じてしまう気がします。

`gameDatePicker`だとわかりやすいのでは？と思っています。

2021-01-08 09:43 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +    func createGameData() {
`createGameData()`わかりやすい命名だと思います👍

2021-01-08 09:43 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +            "matome": matome as Any,
L58-60の命名はローマ字ではなくていいのでは？
せっかく`setupTextView()`メソッドを参考にしてみるといいかもです！

まあそうなってくるとmatomeという文言も気になってきたので命名変更しますか、、笑

2021-01-08 09:43 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +            "matome": matome as Any,
`https://codic.jp/engine`
このサービスについて調べてみてください！
参考になると思います！

2021-01-08 09:45 UTC, fuchi0741 commented
実際に動作確認はできていないのでFirebaseの権限を貰ってから再度レビューしようと思っているので終わったらメンションつけてください！

あとレビューで気になるところがあれば言ってください！

2021-01-08 17:35 UTC, hidec-7 commented
> @hidec-7
> 
> https://support.google.com/firebase/answer/7000272?hl=ja
> ひでとさんすいません。アカウントの権限が追加できるようなので追加していただいてもよろしいですか？？
> 以下のアドレスを追加お願いします！
> [fuchi.kazuma@gmail.com](mailto:fuchi.kazuma@gmail.com)
> 
> 完了したら教えてください！

@fuchi0741 　メンバー追加しました！

2021-01-08 17:36 UTC, hidec-7 commented
> WIPが外れていますが、Model化は別ブランチで実施ということで大丈夫ですか？

あ、ごめんなさい！ややこしいので、別ブランチでやります！

2021-01-08 17:38 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +    @IBOutlet weak private var registerDatePicker: UIDatePicker!
> このDatePickerの日時の使用って送信した日時ではなくて試合した日ですよね？
> `registerDatePicker`だと送信した日時のように感じてしまう気がします。
> 
> `gameDatePicker`だとわかりやすいのでは？と思っています。

試合した日時ですね！
おっしゃる通りだと自分も思うので変更します！

2021-01-08 17:38 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +    func createGameData() {
> `createGameData()`わかりやすい命名だと思います👍

ありがとうございます！

2021-01-08 17:39 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +            "matome": matome as Any,
> L58-60の命名はローマ字ではなくていいのでは？
> せっかく`setupTextView()`メソッドを参考にしてみるといいかもです！
> 
> まあそうなってくるとmatomeという文言も気になってきたので命名変更しますか、、笑

修正します！笑

2021-01-08 17:39 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +            "matome": matome as Any,
> `https://codic.jp/engine`
> このサービスについて調べてみてください！
> 参考になると思います！

ありがとうございます！
こんなのがあるんですね！
参考になります！

2021-01-08 17:53 UTC, hidec-7 commented
@fuchi0741 
指摘部分修正、コメントしました！

2021-01-09 15:49 UTC, hidec-7 commented
@fuchi0741 　修正を忘れていた部分があったので、追加で修正しました

2021-01-09 17:57 UTC, fuchi0741 commented
これ日付が細かすぎる気がしますが、調整した仕様の方がいいのではないでしょうか？
試合の日の時間までいいと思うのですがどう思いますか？

<img width="322" alt="スクリーンショット 2021-01-10 2 55 29" src="https://user-images.githubusercontent.com/50318372/104105107-5adc9900-52ef-11eb-8f94-2e2e5efa5b2b.png">

2021-01-09 18:02 UTC, fuchi0741 requested changes
@hidec-7 一点指摘しました！

2021-01-09 18:02 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +        guard let opponentScore = opponentScoreTextField.text else { return }
ここでguard文を使用する必要はないかと思いました。

- 他の(firstHalf, secondHalf)はただ宣言をしていて統一した方が良さそうだから
- またUITextField.textの初期値は""となっておりnilになるケースが今のところ思いつかないから

2021-01-09 18:04 UTC, fuchi0741 reviewed
追加ですmm

2021-01-09 18:04 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +        let date: String = "\(gameDatePicker.date)"
`date`だとdate型だと思ってしまうのでString型であることを伝えたいです。
dateStringという命名がわかりやすいと思いましたmm

2021-01-09 18:05 UTC, fuchi0741 commented
動作確認はしましたが、特に問題なさそうでした。
質問ですが、データが登録されない条件などはありますか？(例えば全て空欄で登録ボタンを押した時とか？)

2021-01-09 18:09 UTC, hidec-7 commented
> これ日付が細かすぎる気がしますが、調整した仕様の方がいいのではないでしょうか？
> 
> 試合の日の時間までいいと思うのですがどう思いますか？
> 
> 
> 
> <img width="322" alt="スクリーンショット 2021-01-10 2 55 29" src="https://user-images.githubusercontent.com/50318372/104105107-5adc9900-52ef-11eb-8f94-2e2e5efa5b2b.png">
> 
> 

試合の日の時間までがいいですね！
自分の勉強不足なんですけど、これってカスタマイズ？できるんですか？

2021-01-09 18:10 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +        let date: String = "\(gameDatePicker.date)"
修正します！

2021-01-09 18:11 UTC, hidec-7 commented
> 動作確認はしましたが、特に問題なさそうでした。
> 
> 質問ですが、データが登録されない条件などはありますか？(例えば全て空欄で登録ボタンを押した時とか？)

あります！
チーム名、スコアが空欄の場合登録されないようにしたいと思ってます

2021-01-09 18:16 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +        guard let opponentScore = opponentScoreTextField.text else { return }
ここのtextfieldが空欄の場合、その後の処理をしないように。って感じで使ってみたんですけど、この書き方違いますかね？

2021-01-09 18:16 UTC, fuchi0741 commented
> あります！
> 日付、チーム名、スコアが空欄の場合登録されないようにしたいと思ってます
別チケットで大丈夫ですが、上記の条件に当てはまる場合はアラートを出す機能作りましょう！

2021-01-09 18:17 UTC, fuchi0741 commented
> 自分の勉強不足なんですけど、これってカスタマイズ？できるんですか？

はい！できるはずです！
基本的にはなんでもできる前提でいた方がいいです！
それがプログラミングの良さなので！

2021-01-09 18:18 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +        guard let opponentScore = opponentScoreTextField.text else { return }
`textfieldが空欄の場合`

これブレイクポイントで確認していただいたらわかるのですが、""となるので値がある状態なんですよね！もともと
確認してみてください！

2021-01-09 18:18 UTC, hidec-7 commented
> はい！できるはずです！
> 
> 基本的にはなんでもできる前提でいた方がいいです！
> 
> それがプログラミングの良さなので！

そうなんですね！
わかりました！
やってみます！

2021-01-09 18:19 UTC, hidec-7 commented
> > あります！
> 
> > 日付、チーム名、スコアが空欄の場合登録されないようにしたいと思ってます
> 
> 
> 
> 別チケットで大丈夫ですが、上記の条件に当てはまる場合はアラートを出す機能作りましょう！
> 
> 

了解しました！

2021-01-09 18:23 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +        guard let opponentScore = opponentScoreTextField.text else { return }
> @hidec-7 
> 
> `textfieldが空欄の場合`
> 
> 
> 
> これブレイクポイントで確認していただいたらわかるのですが、""となるので値がある状態なんですよね！もともと
> 
> 確認してみてください！してみてください！

あ！そうなんですね！
これじゃプログラム上空欄にはならないんですね！

2021-01-10 17:44 UTC, hidec-7 commented
@fuchi0741 　指摘部分修正しました！
確認よろしくお願いします！

2021-01-11 07:16 UTC, fuchi0741 requested changes
@hidec-7 コメントしましたー！

2021-01-11 07:16 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +        let dateString: String = "\(setupDate.string(from: gameDatePicker.date))"
L47-49は1つのまとまった処理なのでメソッド化しましょう！

`let dateString = getGameStartTime()`

```swift
private func getGameStartTime() -> String {
        let setupDate = DateFormatter()
        setupDate.dateFormat = "yyyy年MM月dd日HH時mm分"
        return "\(setupDate.string(from: gameDatePicker.date))"
}
```

2021-01-11 07:16 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +        let dateString: String = "\(setupDate.string(from: gameDatePicker.date))"
L47の型は書く必要がない型ですね！(クラスをインスタンス化するときはあまり型を書かないイメージはあります。)
なので型推論を利用しましょう！
`let setupDate = DateFormatter()`

2021-01-11 15:45 UTC, hidec-7 commented
@fuchi0741 修正しました！

2021-01-12 12:40 UTC, fuchi0741 approved these changes
@hidec-7 LGTM👍

2021-01-12 13:52 UTC, merged