登録画面 登録ボタンタップ アラート表示
hidec-7/MySoccerNoteApp pull request #44
Opened 2021-01-12 17:20 UTC by hidec-7

**clone コマンド**
git clone -b feature/add-alretDisplay https://github.com/hidec-7/SoccerNoteDev.git

**Trello**
登録時のアラート表示

**概要**
登録画面の登録ボタンをタップ時に、チーム名・スコアが入力されていない場合にアラートを表示して登録できないように実装。

**レビューで見て欲しいポイント**
アラート表示の実装方法に問題はないか。
アラート表示するか否かの条件分岐のコードはメソッド化した方がいいのでしょうか？
タイトル、メッセージ等の命名に問題はないか。

**実機build/期待通りの挙動をするか**
OK

**レビュー依頼**
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741

2021-01-12 19:02 UTC, fuchi0741 requested changes
@hidec-7 コメントしました！

2021-01-12 19:02 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +        }else{
elseの両端は半角スペースを入れましょう！

`} else {`

2021-01-12 19:02 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +        if teamTextField.text == "" || myScoreTextField.text == "" || opponentScoreTextField.text == "" {
`teamTextField.text == ""`
ここは`isEmpty`プロパティを使用したほうがわかりやすそうです！

2021-01-12 19:03 UTC, fuchi0741 commented
> アラート表示するか否かの条件分岐のコードはメソッド化した方がいいのでしょうか？

アラート実装に関する箇所をメソッド化した方がわかりやすいと思いました！

2021-01-13 05:03 UTC, hidec-7 commented
@fuchi0741 　修正しました！

2021-01-13 05:42 UTC, fuchi0741 requested changes
@hidec-7 コメントしました！

2021-01-13 05:42 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +        if teamTextField.text?.isEmpty == true || myScoreTextField.text?.isEmpty == true || opponentScoreTextField.text?.isEmpty == true {
` teamTextField.text?.isEmpty == true`のtrueは冗長なため削除でいいかと思います！
isEmptyなどのBool値の初期値がtrueのため、あえて書かなくてもisEmptyがtrueと伝わるためです！

2021-01-13 05:42 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +            present(alert, animated: true, completion: nil)
メソッド化しましょー！

2021-01-13 05:47 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameRegisterViewController.swift
> +            present(alert, animated: true, completion: nil)
あ、メソッド化する部分勘違いしてました！

2021-01-13 05:50 UTC, hidec-7 commented
@fuchi0741 修正こんな感じでいいですかね？

2021-01-13 05:52 UTC, fuchi0741 approved these changes
@hidec-7 LGTM👍

2021-01-13 05:53 UTC, merged