試合データ（Read)実装
hidec-7/MySoccerNoteApp pull request #49
Opened 2021-01-18 03:05 UTC by hidec-7

**clone コマンド**
git clone -b feature/read-gameData-firebase https://github.com/hidec-7/SoccerNoteDev.git

**Trello**
CRUD(R:読み取り)

**概要**
試合データを試合管理画面に読み込みをしました。

**レビューで見て欲しいポイント**
コードの書き方に問題はないか。
命名に問題はないか。
その他気になる所があればご指摘お願いします。

**実機build/期待通りの挙動をするか**
OK

**レビュー依頼**
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741

2021-01-18 13:31 UTC, fuchi0741 commented
1点気になる仕様があるので共有させてくださいー！

一番最新に登録された試合データが試合一覧画面の一番最後に表示されているのですが、問題ないですか？？
個人的には一番上にくる仕様にした方が登録されたことがわかるのでいいと思います！

2021-01-18 13:43 UTC, hidec-7 commented
> 1点気になる仕様があるので共有させてくださいー！
> 
> 
> 
> 一番最新に登録された試合データが試合一覧画面の一番最後に表示されているのですが、問題ないですか？？
> 
> 個人的には一番上にくる仕様にした方が登録されたことがわかるのでいいと思います！

あ！それ自分も思って迷ってました！笑
変更したいと思います！

2021-01-18 13:44 UTC, fuchi0741 reviewed
@hidec-7 コメントしました💡

2021-01-18 13:44 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +        let date = cell.viewWithTag(4) as! UILabel
viewWithTag(1)の1のような、いわいるマジックナンバーと呼ばれるものは基本的に許容できないです！
なのでviewWithTagを使用しない方法を模索してみてください！

わからなくなったら聞いてください！

2021-01-18 15:52 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +        let date = cell.viewWithTag(4) as! UILabel
> viewWithTag(1)の1のような、いわいるマジックナンバーと呼ばれるものは基本的に許容できないです！
> なのでviewWithTagを使用しない方法を模索してみてください！
> 
> わからなくなったら聞いてください！

@fuchi0741 

![image](https://user-images.githubusercontent.com/66632738/104936038-5a2ebb80-59ef-11eb-975b-bf49209e1491.png)

チャレンジしたのですが、できなかったです。
まず自分の認識の確認なのですが、この画像のクラスのUILabelを試合管理画面のViewControllerのcellForRowAtに持って来て、試合データを取得する？のかなと思っているのですが間違ってますか？
間違いないとしたら、その試合管理画面のCellのクラスからViewControllerに持って来る手段がわからないです、、、
ご教示お願いできないでしょうか。

2021-01-18 15:59 UTC, hidec-7 commented
> > 1点気になる仕様があるので共有させてくださいー！
> > 一番最新に登録された試合データが試合一覧画面の一番最後に表示されているのですが、問題ないですか？？
> > 個人的には一番上にくる仕様にした方が登録されたことがわかるのでいいと思います！
> 
> あ！それ自分も思って迷ってました！笑
> 変更したいと思います！


すいません、Cellを上に追加する方法が全くわかりませんでした。
ググってみても全然ヒットしなくて、完全にノックアウト状態です。
わからなすぎて何も試すこともできませんでした。
アドバイス頂けないでしょうか。

2021-01-18 17:33 UTC, fuchi0741 commented
@hidec-7 以下がヒントになります💡
恐らく`GameManagementTableViewCellCell`の`opponentTeamLabel`プロパティを使用したいと思っているはずです。
ただ、cellの型を確認すると`UITableViewCell`でした🙍‍♂️

`UITableViewCell`のプロパティにひでとさんが作成したプロパティが入っているかと言われると入っていないんですよね😖





<img width="1159" alt="スクリーンショット 2021-01-19 2 28 50" src="https://user-images.githubusercontent.com/50318372/104946843-1abb9b80-59fe-11eb-939c-f607f07d17df.png">

2021-01-18 17:48 UTC, fuchi0741 requested changes
@hidec-7 コメント追加💡

2021-01-18 17:48 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +        })
TODO: モデル化として別チケット対応予定

2021-01-18 17:48 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
>      //今後変更の可能性あり
ここのコメントは不要になったのであれば変更しましょう💡

2021-01-18 17:48 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +        let date = cell.viewWithTag(4) as! UILabel
コメントしました💡

2021-01-18 17:48 UTC, fuchi0741 commented on SoccerNoteApp/Model/GameDataModel.swift
> +    }
このメソッドに書く必要がないかと思いました。
(引数にdictionaryがありますが、これは今回の辞書型でしか対応できないのであまり引数の恩恵が受けられないです！)
→"team"などの固定値を既に決まってしまっているため。

そのため、getGameDataメソッド内に上記の処理を記述する形でいいように感じました。

2021-01-18 17:48 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +                var gameData = GameDataModel()
ここはletでも問題ないですね！
基本的にlet と var 両方使用できる場合は積極的にletを使用しましょー！

2021-01-18 17:48 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +            self.gameDataArray = []
ここも不要だと思いますー！
必要であれば教えてくださいー！

2021-01-19 04:25 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +        })
ここが試合データのモデリングになる所ですか？

2021-01-19 04:30 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +        })
getGameDataメソッドなどのREADの処理に関連する箇所ですね〜

2021-01-19 05:42 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +            self.gameDataArray = []
これL39も不要ですか？

2021-01-19 05:43 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +            self.gameDataArray = []
L40のみですね〜

2021-01-19 06:00 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +                var gameData = GameDataModel()
![image](https://user-images.githubusercontent.com/66632738/104993685-8e918e80-5a66-11eb-8dc3-32a47c999160.png)

let にすると値が変わるので var に変更しろとエラーが出ました。

2021-01-19 06:01 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +                var gameData = GameDataModel()
setFromDictiobaryのメソッドの指摘を修正すれば問題ないですかね？

2021-01-19 06:24 UTC, hidec-7 commented
> @hidec-7 以下がヒントになります💡
> 恐らく`GameManagementTableViewCellCell`の`opponentTeamLabel`プロパティを使用したいと思っているはずです。
> ただ、cellの型を確認すると`UITableViewCell`でした🙍‍♂️
> 
> `UITableViewCell`のプロパティにひでとさんが作成したプロパティが入っているかと言われると入っていないんですよね😖
> 
> <img alt="スクリーンショット 2021-01-19 2 28 50" width="1159" src="https://user-images.githubusercontent.com/50318372/104946843-1abb9b80-59fe-11eb-939c-f607f07d17df.png">

`UITableViewCell`のプロパティに自分の作成したプロパティを入れ方がわからないです。

2021-01-19 06:28 UTC, hidec-7 commented on SoccerNoteApp/Model/GameDataModel.swift
> +    }
getGameDataメソッド内での記述ができなかったです。
どのように処理を記述するのがわからなくて、、、

2021-01-19 06:45 UTC, fuchi0741 commented on SoccerNoteApp/Model/GameDataModel.swift
> +    }
```Swift
gameData.gameDate = dictionarySnapData["gameDate"] as! String`
こんな感じでできそうじゃないですか？

2021-01-19 06:46 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +                var gameData = GameDataModel()
あ、`setFromDictionary`をなくす前提で話していました。
もし無くせばletでいけるかと

2021-01-19 06:47 UTC, fuchi0741 commented
> `UITableViewCell`のプロパティに自分の作成したプロパティの入れ方がわからないです。

厳密には入れるわけではないですー
キーワードはキャストですmm

2021-01-19 06:53 UTC, hidec-7 commented on SoccerNoteApp/Model/GameDataModel.swift
> +    }
あ、できました！
記事する箇所を間違えてました🙇‍♂️

2021-01-19 06:56 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +                var gameData = GameDataModel()
![image](https://user-images.githubusercontent.com/66632738/104998423-8dfcf600-5a6e-11eb-86a7-a6e22957048b.png)

`setFromDictionary`無くしてもできないですね。

2021-01-19 06:59 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +                var gameData = GameDataModel()
@hidec-7 すいません！自分が勘違いしてました！
varのままで問題ないですね！

2021-01-19 07:01 UTC, hidec-7 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +                var gameData = GameDataModel()
わかりました！mm

2021-01-19 07:14 UTC, hidec-7 commented
> > `UITableViewCell`のプロパティに自分の作成したプロパティの入れ方がわからないです。
> 
> 厳密には入れるわけではないですー
> キーワードはキャストですmm

![image](https://user-images.githubusercontent.com/66632738/105000114-4a57bb80-5a71-11eb-806a-83a7011c4a31.png)

違うと思うんですけど、こんな感じじゃないですよね？

2021-01-19 07:51 UTC, fuchi0741 commented
> > > `UITableViewCell`のプロパティに自分の作成したプロパティの入れ方がわからないです。
> > 
> > 
> > 厳密には入れるわけではないですー
> > キーワードはキャストですmm
> 
> ![image](https://user-images.githubusercontent.com/66632738/105000114-4a57bb80-5a71-11eb-806a-83a7011c4a31.png)
> 
> 違うと思うんですけど、イメージこんな感じじゃないですよね？

そうですねーー違いますね😓

2021-01-19 16:39 UTC, hidec-7 commented
> > > > `UITableViewCell`のプロパティに自分の作成したプロパティの入れ方がわからないです。
> > > 
> > > 
> > > 厳密には入れるわけではないですー
> > > キーワードはキャストですmm
> > 

![image](https://user-images.githubusercontent.com/66632738/105064312-0c35b880-5ac0-11eb-9379-ae3b00ac3fbd.png)

何となくLabelを持って来る所までできたんですけど、多分あとこのそれぞれのLabelにそれぞれの`gameData`を取得させればできるのかなって感じなんですけど、合ってます？笑
↑言葉が変だったらすいません。

2021-01-19 16:44 UTC, fuchi0741 commented
`let cell = gameManagementTableView.dequeueReusableCell(withIdentifier: cellId, for: indexPath) as! GameManagementTableViewCell`

これが答えですmm

2021-01-19 16:51 UTC, hidec-7 commented
> `let cell = gameManagementTableView.dequeueReusableCell(withIdentifier: cellId, for: indexPath) as! GameManagementTableViewCell`
> 
> 
> 
> これが答えですmm
> 
> CellをUITablelViewCellからGameManagementTableViewCellに型がキャストされているはずです。
> 
> 確認してみてくださいー！

なるほどです！！
キャストをちゃんとわかっていなかったです。笑

2021-01-19 16:52 UTC, fuchi0741 commented
今回で型の重要性が少しは理解できたのではと思っていますー

2021-01-19 16:56 UTC, hidec-7 commented
> 今回で型の重要性が少しは理解できたのではと思っていますー

できました！
すごく基本的なことを理解できていなくてダメダメですが、今回で少し理解できてよかったですｍｍ
ありがとうございます！

2021-01-19 17:14 UTC, hidec-7 commented
@fuchi0741 

![image](https://user-images.githubusercontent.com/66632738/105068254-13f75c00-5ac4-11eb-87a2-d2fd7e61bae8.png)

ビルドしたらここでエラーが出てクラッシュしてしまったんですけど、原因がわからないです。
nilチェックで引っかかったのかなと思うのですが、、、

2021-01-19 17:17 UTC, fuchi0741 commented
nilだからクラッシュしたのはあっていますね！

2021-01-19 17:22 UTC, hidec-7 commented
> nilだからクラッシュしたのはあっていますね！

試合管理画面に表示させるのが、日付、チーム名、スコアのラベルしかなくて、前半、後半、まとめはないから？とかですか？

2021-01-19 17:26 UTC, hidec-7 commented
> nilだからクラッシュしたのはあっていますね！

わかりました！
空の値を入れないといけない？ですか？
`??  ""`

2021-01-19 17:30 UTC, hidec-7 commented
> nilだからクラッシュしたのはあっていますね！

@fuchi0741 

![image](https://user-images.githubusercontent.com/66632738/105071018-68500b00-5ac7-11eb-9efa-e101c67366a7.png)

できました！

2021-01-19 17:33 UTC, hidec-7 commented
@fuchi0741 修正しました！
確認よろしくお願いします！

2021-01-19 17:35 UTC, hidec-7 commented
> > > 1点気になる仕様があるので共有させてくださいー！
> > > 一番最新に登録された試合データが試合一覧画面の一番最後に表示されているのですが、問題ないですか？？
> > > 個人的には一番上にくる仕様にした方が登録されたことがわかるのでいいと思います！
> > 
> 
> @fuchi0741 　すいません、Cellを上に追加する方法も全くわかりませんでした。
> ググってみても全然ヒットしなくて、完全にノックアウト状態です。
> わからなすぎて何も試すこともできませんでした。
> アドバイス頂けないでしょうか。

あ、あとすいませんここが全然わからなくてアドバイス頂けないでしょうか。

2021-01-19 17:45 UTC, fuchi0741 commented
> 一番上にくる仕様
配列の順番を逆にすれば、解決できると思いました！

2021-01-20 03:21 UTC, hidec-7 commented
@fuchi0741 指摘部分全ての修正終わりました！
Model化次のタスクでやります！

2021-01-20 03:40 UTC, fuchi0741 requested changes
@hidec-7 1点コメントしました💡

2021-01-20 03:40 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +        dateLabel.text = gameData.gameDate
ここは定数化をあえてしなくても大丈夫そうです。

```swift
let opponentTeamLabel = cell.opponentTeamLabel as UILabel
opponentTeamLabel.text = gameData.team
```

`cell.opponentTeamLabel.text = gameData.team`
と実装した方がコードが読みやすいと思います。

2021-01-20 03:49 UTC, hidec-7 commented
@fuchi0741 　修正しました！

2021-01-20 05:07 UTC, fuchi0741 approved these changes
@hidec-7 一点指摘事項を加えましたが軽微な修正なためLGTM👍 
軽微な修正を実施してからマージお願いしますー！

2021-01-20 05:07 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> +        cell.dateLabel.text = gameData.gameDate
値渡しが続いていますが、実際のUIと順番を揃えたいです。

左上から記述した方が実態と同じなので、

試合日時
相手チーム
自チームスコア
相手チームスコア
前半
後半
まとめ

の順番にプロパティを変更したいです。
ここ以外も確認と修正をお願いしたいです！

2021-01-20 05:08 UTC, fuchi0741 commented
先にいっておくと、READのMoedl化に伴って新たに必要になる技術は
delegateとProtocal または closure です。

2021-01-20 05:12 UTC, merged