[WIP] 試合データRead Model化
hidec-7/MySoccerNoteApp pull request #52
Opened 2021-01-22 15:48 UTC by hidec-7

2021-01-22 16:15 UTC, fuchi0741 commented
あれ、もゆもう少しでできそうですがどこで詰まっている感じです？

2021-01-22 16:19 UTC, hidec-7 commented
> あれ、もゆもう少しでできそうですがどこで詰まっている感じです？

GameManagementViewControllerにGameDataReadModelクラスのメソッドを渡すとことかですかね？

詰まってるのは、reloadの所で引数用いてどうやって実装するのか　？？　な状態です。

2021-01-22 16:23 UTC, fuchi0741 commented
`GameManagementViewControllerにGameDataReadModelクラスのメソッドを渡すとことかですかね？`
それも必須ですね！

ひでとさんが定義してtableはどのような働きをしているのか引数という観点から見てみてください！

2021-01-22 17:03 UTC, hidec-7 commented
> `GameManagementViewControllerにGameDataReadModelクラスのメソッドを渡すとことかですかね？`
> それも必須ですね！
> 
> ひでとさんが定義してtableはどのような働きをしているのか引数という観点から見てみてください！
> 
> やばかったらいってくださいー！

@fuchi0741 　やっぱりギブアップです、、、
tableは`reloadData()`を使えるようにする？のかなって思ってます。

2021-01-22 17:05 UTC, fuchi0741 commented
それも含めてレクチャーって感じですかね？

2021-01-22 17:06 UTC, hidec-7 commented
> それも含めてレクチャーって感じですかね？

そうですね、含めてお願いしたいです。

2021-01-24 02:22 UTC, hidec-7 commented
@fuchi0741 昨日のバグ何ですけど、かなりしょーもないものでした。笑
何てテキストで説明すればいいのかわからないので、またレクチャーの時さらってお話しますね笑
とりあえずもう問題はないです笑

ですが、バグの修正は大丈夫だったんですけど、やっぱりリロードがされていないのか試合管理画面に表示がされていません。
Model化のしてるコードだとできないです。（ビルド時のエラーはなしです）
Model化前のコードだと問題なく挙動も上手く行きます。

2021-01-30 06:23 UTC, hidec-7 commented
@fuchi0741  

**Read処理のModel化**

修正しました！
Delegateを用いてやってます！

ビルド時の挙動問題なしです！
 
プロトコルでメソッドを定義し、処理を任せる、任される側の認識が理解できました！
スタティックプロパティとインスタンスプロパティの使い分けも今後、意識してやっていきます！

2021-01-30 06:30 UTC, hidec-7 commented
修正漏れがありました。

2021-01-30 08:28 UTC, fuchi0741 requested changes
@hidec-7 コメントしました〜！

2021-01-30 08:28 UTC, fuchi0741 commented on SoccerNoteApp/Model/GameDataReadModel.swift
> +    static func getGameData() {
細かいですが、`getGameData`ではなく`fetchGameData`の方が適していると思います。
DBから値を取得するメソッドの場合はfetchをよく見るからなんですよね

調べてみたらいい感じの記事が出てきました
https://tech.mof-mof.co.jp/blog/method-name/

2021-01-30 08:28 UTC, fuchi0741 commented on SoccerNoteApp/Controller/GameManagementViewController.swift
> -    var gameDataArray = [GameDataModel]()
`import Firebase`は不要なハズなので削除しましょう！

2021-01-30 08:28 UTC, fuchi0741 commented on SoccerNoteApp/Model/GameDataReadModel.swift
> +class GameDataReadModel {
ここclassではなくてstructでもいけそうです！
Appleはclassよりもstructを実は推しているので、どっちでも使用可能な場合はstructを使用しましょう！

2021-01-30 14:38 UTC, hidec-7 commented
@fuchi0741 修正しました！

2021-01-30 15:29 UTC, fuchi0741 approved these changes
@hidec-7 LGTM👍

2021-01-30 15:44 UTC, merged