試合管理画面 UITableView 実装
hidec-7/MySoccerNoteApp pull request #9
Opened 2020-11-07 06:03 UTC by hidec-7

**clone コマンド**
git clone -b feature/add-UI-gamemanagement-TableView https://github.com/hidec-7/SoccerNoteDev.git

**Trello**
試合管理画面 試合管理TableView実装

**概要**
試合管理画面のTableViewを実装しました

**レビューで見て欲しいポイント**
コードの書き方に問題はないか。

**実機build/期待通りの挙動をするか**
OK

※UI変更した場合のみ記述

**11 Pro や SE など大きさが異なる端末のレイアウトが崩れていないか？**
OK 

**レビュー依頼**
※[WIP]の場合は全て消して依頼しないようにしてください
@fuchi0741

**補足**
このブランチではTableViewのみの実装でしたが、TableViewCellのファイルも作成しコードを書いてしまったので次のブランチでCell用のXibを作成し、XibとTableViewCellファイルの紐付け、最終TableViewのViewControllerとの紐付けをして行きたいと思います。

2020-11-07 14:32 UTC, fuchi0741 commented
ダークモード非対応って実装まだでしたっけ？

2020-11-07 14:33 UTC, hidec-7 commented
> ダークモード非対応って実装まだでしたっけ？
> 
> (実機で確認したら黒かったので確認しました。)

あ、まだ実装してないです！！

2020-11-07 14:40 UTC, fuchi0741 requested changes
@hidec-7 レビューしました！
細かいところの指摘のみですが修正お願いしますー！
(スペース関連の指摘ですが、なんでもなくせばいいという訳ではないです。
スペースを開けることでコードがみやすくなるのであれば、あえてスペースを開けるという方法もあります。ただ、特に理由がないのであれば基本削除で！)

2020-11-07 14:40 UTC, fuchi0741 commented on SoccerNoteApp/GameManagementViewController.swift
> +    private let cellId = "cellId"
これは仮の実装でしょうか？(これからCellを実装するけど一旦buildさせるためにつけたのかどうか気になります)

もし仮の実装で今後削除する予定があるのであれば、その旨のコメントが欲しいです！

2020-11-07 14:40 UTC, fuchi0741 commented on SoccerNoteApp/GameManagementViewController.swift
> +
余計なスペースは消しましょう！

2020-11-07 14:40 UTC, fuchi0741 commented on SoccerNoteApp/GameManagementViewController.swift
> +        return 80
これもなぜ80にしたのか気になりました？
今後変更する予定なのであればコメントをお願いします。
(とりあえず80にしたと思うのですが、現場だと何故なのかとかや仮で置いているだけなのかわからないので、面倒臭いですがお願いします)

2020-11-07 14:40 UTC, fuchi0741 commented on SoccerNoteApp/GameManagementViewController.swift
> +        return 100
同上

2020-11-07 14:40 UTC, fuchi0741 commented on SoccerNoteApp/GameManagementViewController.swift
> +
余計なスペース

2020-11-07 14:40 UTC, fuchi0741 commented on SoccerNoteApp/GameManagementViewController.swift
> +
余計なスペース

2020-11-07 14:40 UTC, fuchi0741 commented on SoccerNoteApp/GameManagementViewController.swift
> +
余計なスペース

2020-11-07 14:41 UTC, fuchi0741 commented on SoccerNoteApp/GameManagementViewController.swift
> +    private let cellId = "cellId"
```swift
private let cellId = "cellId"

ここの話ですね！

2020-11-07 14:47 UTC, fuchi0741 commented
コミットの分け方ですが、特に問題はないと思います(あとは好みの問題ですねmm)

個人的にはですが、1つめと2つ目はコミット分けなくても問題なかったかなと思います！
→ViewControllerのファイル追加とかでも問題伝わるかなーって感じですmm

あとは

GameManagementTableViewControllerなど固有名詞をあまりcommitでは使用しない方がいいかもです！
(レビューした人からすると、どんなファイルかわからないです！今回はファイル数が少ないので問題ないですが現場だとファイルが死ぬほどあるので、、、)
なので試合管理画面?など非エンジニアでもわかる言葉とチョイスするといいと思いました！


<img width="695" alt="スクリーンショット 2020-11-07 23 42 58" src="https://user-images.githubusercontent.com/50318372/98444067-fec09180-2152-11eb-95fd-fb56862e566a.png">

2020-11-07 14:53 UTC, fuchi0741 commented
https://qiita.com/y-some/items/8bc06567eee18dfeafbb

コメントの書き方って実はたくさんあるので、知っておくといいかもです！
(ドキュメントコメント、docコメントっていいます)

現場のソースコードを読むとコメントの量にびっくりすると思いますmm

2020-11-07 15:14 UTC, hidec-7 commented
> 
> 
> コミットの分け方ですが、特に問題はないと思います(あとは好みの問題ですねmm)
> 
よかったです！
> 
> 
> 個人的にはですが、1つめと2つ目はコミット分けなくても問題なかったかなと思います！
> 
> →ViewControllerのファイル追加とかでも問題伝わるかなーって感じですmm
> 
わかりました！
> 
> 
> あとは
> 
> 
> 
> GameManagementTableViewControllerなど固有名詞をあまりcommitでは使用しない方がいいかもです！
> 
> (レビューした人からすると、どんなファイルかわからないです！今回はファイル数が少ないので問題ないですが現場だとファイルが死ぬほどあるので、、、)
> 
> なので試合管理画面?など非エンジニアでもわかる言葉とチョイスするといいと思いました！
> 
なるほどです！
なんて言うか、ファイル名そのままがいいのかなと思ってそうしてました。笑
> 
>

2020-11-07 15:20 UTC, hidec-7 commented on SoccerNoteApp/GameManagementViewController.swift
> +    private let cellId = "cellId"
これからCellを実装するけど一旦buildさせるためにつけた。です！
今後削除すると思います！

2020-11-07 15:20 UTC, hidec-7 commented on SoccerNoteApp/GameManagementViewController.swift
> +
了解です！

2020-11-07 15:24 UTC, fuchi0741 commented
>なんて言うか、ファイル名そのままがいいのかなと思ってそうしてました。笑

まあほんと好みの問題です、、!
ただ非エンジニアでもわかる画面の名前の書くのが多いイメージですね、、、！

2020-11-07 15:25 UTC, hidec-7 commented on SoccerNoteApp/GameManagementViewController.swift
> +        return 80
なるほどです！

ビルドして繰り返し確認しながら、これくらいの幅がUI的に見やすいかなっていろんな幅を試しながらやりました
もしかしたら変更する可能性もあります

2020-11-07 15:27 UTC, hidec-7 commented on SoccerNoteApp/GameManagementViewController.swift
> +        return 100
これは結構適当と言うかこれくらいが丁度いいかなって何となくです。あまりよくないと思うのですが。

2020-11-07 15:27 UTC, hidec-7 commented on SoccerNoteApp/GameManagementViewController.swift
> +
修正します！

2020-11-07 15:28 UTC, hidec-7 commented on SoccerNoteApp/GameManagementViewController.swift
> +
修正します！

2020-11-07 15:28 UTC, hidec-7 commented on SoccerNoteApp/GameManagementViewController.swift
> +
修正します！

2020-11-07 15:34 UTC, hidec-7 commented
> @hidec-7 レビューしました！
> 
> 細かいところの指摘のみですが修正お願いしますー！
> 
> (スペース関連の指摘ですが、なんでもなくせばいいという訳ではないです。
> 
> スペースを開けることでコードがみやすくなるのであれば、あえてスペースを開けるという方法もあります。ただ、特に理由がないのであれば基本削除で！)

了解です！

2020-11-07 15:34 UTC, hidec-7 commented
> https://qiita.com/y-some/items/8bc06567eee18dfeafbb
> 
> 
> 
> コメントの書き方って実はたくさんあるので、知っておくといいかもです！
> 
> (ドキュメントコメント、docコメントっていいます)
> 
> 
> 
> 現場のソースコードを読むとコメントの量にびっくりすると思いますmm

引用ありがとうございます！！
参考にします！

2020-11-07 16:31 UTC, hidec-7 commented
> >なんて言うか、ファイル名そのままがいいのかなと思ってそうしてました。笑
> 
> 
> 
> まあほんと好みの問題です、、!
> 
> ただ非エンジニアでもわかる画面の名前の書くのが多いイメージですね、、、！
> 
> 
> 
> 

わかりました！

2020-11-09 03:05 UTC, fuchi0741 requested changes
@hidec-7 
ソースコードに指摘該当箇所にコメントの追加をお願いしますmm

2020-11-09 03:16 UTC, hidec-7 commented
コメント内容は「余計なスペース修正」とかですかね？

2020-11-09 03:19 UTC, hidec-7 commented
> @hidec-7 
> 
> ソースコードに指摘該当箇所にコメントの追加をお願いしますmm

なぜCellの高さを80にしたかとか、なぜCellの数を100にしたかとかのコメントを追加したらいいんですかね？

2020-11-09 03:27 UTC, fuchi0741 commented
> > @hidec-7
> > ソースコードに指摘該当箇所にコメントの追加をお願いしますmm
> 
> なぜCellの高さを80にしたかとか、なぜCellの数を100にしたかとかのコメントを追加したらいいんですかね？

そうです！
暫定処理なのかどうかを書いて欲しいです！
(個人開発だと問題ないので修正するかは任せますーー)

2020-11-10 00:39 UTC, hidec-7 commented
> > > @hidec-7
> > > ソースコードに指摘該当箇所にコメントの追加をお願いしますmm
> > 
> > 
> > なぜCellの高さを80にしたかとか、なぜCellの数を100にしたかとかのコメントを追加したらいいんですかね？
> 
> そうです！
> 暫定処理なのかどうかを書いて欲しいです！
> (個人開発だと問題ないので修正するかは任せますーー)

返信遅くなりました！
修正しました！

2020-11-10 01:28 UTC, hidec-7 commented
すいません、スペースもう一度少し修正しました。

2020-11-10 08:18 UTC, hidec-7 commented
すいません、変更と追加がcommitが多くなってしまいました。

2020-11-10 23:10 UTC, fuchi0741 approved these changes
@hidec-7 LGTM！

2020-11-10 23:13 UTC, fuchi0741 commented
commitめっちゃ分けてくれてありがとうございます！

今回修正で4つcommitをうってくれたと思いますが、今回は1つでもよかったかなと思いました！
例えば、指摘事項修正ってメッセージで1つのcommitでもいいかと思いました！

2020-11-10 23:31 UTC, fuchi0741 commented
あとこれも細かいので、そうなんだ程度でスルーして欲しいのですが、

//今後変更の可能性あり

↑このコメントだと、どんな時に修正をするのか？がわからないので、なんであとで修正するのか？
(もし2年後に //今後変更の可能性あり って見たら困惑すると思います笑
実際自分が現場で3年前に書かれた //今後変更の可能性あり みたいなコメント消しました笑)

2020-11-11 00:53 UTC, hidec-7 commented
> commitめっちゃ分けてくれてありがとうございます！
> 
> 
> 
> 今回修正で4つcommitをうってくれたと思いますが、今回は1つでもよかったかなと思いました！
> 
> 例えば、指摘事項修正ってメッセージで1つのcommitでもいいかと思いました！ 

わかりました！

2020-11-11 01:01 UTC, hidec-7 commented
> あとこれも細かいので、そうなんだ程度でスルーして欲しいのですが、
> 
> 
> 
> //今後変更の可能性あり
> 
> 
> 
> ↑このコメントだと、どんな時に修正をするのか？がわからないので、なんであとで修正するのか？
> 
> (もし2年後に //今後変更の可能性あり って見たら困惑すると思います笑
> 
> 実際自分が現場で3年前に書かれた //今後変更の可能性あり みたいなコメント消しました笑)

なるほどです！
参考にします！

2020-11-11 01:01 UTC, merged